const datos=[
{
"BUSCADOR":[
 {
  "SECCION CODG": 1336,
  "SECCION": 1336,
  "LETRA": "X",
  "EDAD": 42,
  "NOMBRE JUEZ": "ADAN GERARDO GONZALEZ LEDEZMA",
  "COLONIA": "NARVARTE",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 3313521775
 },
 {
  "SECCION CODG": "0975",
  "SECCION": 975,
  "LETRA": "X",
  "EDAD": 42,
  "NOMBRE JUEZ": "AGRIPINA SOLEDAD NAVA HERNANDEZ",
  "COLONIA": "VALLE DEL TOPO CHICO",
  "SUPERVISOR ": "VIRIDIANA GONZALEZ",
  "TELEFONOS DE CONTACTO": 8110355199
 },
 {
  "SECCION CODG": 1516,
  "SECCION": 1516,
  "LETRA": "X",
  "EDAD": 48,
  "NOMBRE JUEZ": "ALEJANDRO JAVIER DE LEON REYNA",
  "COLONIA": "LOMA LINDA",
  "SUPERVISOR ": "CLAUDIA ESPINOSA",
  "TELEFONOS DE CONTACTO": 8114127012
 },
 {
  "SECCION CODG": 1466,
  "SECCION": 1466,
  "LETRA": "X",
  "EDAD": 62,
  "NOMBRE JUEZ": "ALEJANDRO MANUEL SALINAS GARZA",
  "COLONIA": "SAN BERNABE XV SECTOR (FOMERREY 110)",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8124110442
 },
 {
  "SECCION CODG": 1386,
  "SECCION": 1386,
  "LETRA": "X",
  "EDAD": 68,
  "NOMBRE JUEZ": "ALMA ESTHER AYALA ESTRADA",
  "COLONIA": "SAN ANGEL SUR",
  "SUPERVISOR ": "CINTHIA TORRES",
  "TELEFONOS DE CONTACTO": 8117297340
 },
 {
  "SECCION CODG": 2802,
  "SECCION": "2802-2803-2804-2805",
  "LETRA": "X",
  "EDAD": 65,
  "NOMBRE JUEZ": "ALMA ESTHER RODRIGUEZ CASTAÑEDA",
  "COLONIA": "REAL CUMBRES",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8125143546
 },
 {
  "SECCION CODG": 1653,
  "SECCION": "1653-1665",
  "LETRA": "X",
  "EDAD": 60,
  "NOMBRE JUEZ": "ALMA RUT CASTILLO HERNANDEZ",
  "COLONIA": "MARIANO ESCOBEDO",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8131012679
 },
 {
  "SECCION CODG": 1066,
  "SECCION": 1066,
  "LETRA": "X",
  "EDAD": 47,
  "NOMBRE JUEZ": "ALMA VIOLETA IÑIGUEZ TORRES",
  "COLONIA": "TALLERES",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8113226793
 },
 {
  "SECCION CODG": 1622,
  "SECCION": 1622,
  "LETRA": "X",
  "EDAD": 53,
  "NOMBRE JUEZ": "ANA GABRIELA PAGAZA OJEDA",
  "COLONIA": "LOMAS DE ANAHUAC",
  "SUPERVISOR ": "GUADALUPE ROCHA",
  "TELEFONOS DE CONTACTO": 8124929519
 },
 {
  "SECCION CODG": 1018,
  "SECCION": 1018,
  "LETRA": "X",
  "EDAD": 57,
  "NOMBRE JUEZ": "ANA LAURA CHAVEZ ORTEGA",
  "COLONIA": "MITRAS CENTRO",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8117914480
 },
 {
  "SECCION CODG": 1563,
  "SECCION": 1563,
  "LETRA": "X",
  "EDAD": 56,
  "NOMBRE JUEZ": "ANDRES ZUÑIGA SEGURA",
  "COLONIA": "LOMAS DE SANTA CECILIA",
  "SUPERVISOR ": "ELIZABETH ARELLANO",
  "TELEFONOS DE CONTACTO": 8112799482
 },
 {
  "SECCION CODG": 1237,
  "SECCION": 1237,
  "LETRA": "X",
  "EDAD": 45,
  "NOMBRE JUEZ": "ANGELICA MARIA SALAS HERRERA",
  "COLONIA": "TANQUES DE GUADALUPE",
  "SUPERVISOR ": "EDSON RANGEL",
  "TELEFONOS DE CONTACTO": 8121603058
 },
 {
  "SECCION CODG": 1410,
  "SECCION": 1410,
  "LETRA": "X",
  "NOMBRE JUEZ": "ARMANDINA RODRIGUEZ HERRERA",
  "COLONIA": "DEL PASEO RESIDENCIAL",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8114876220
 },
 {
  "SECCION CODG": 1448,
  "SECCION": "1448-B",
  "LETRA": "B",
  "EDAD": 29,
  "NOMBRE JUEZ": "ARMANDO ISRAEL SANCHEZ MARTINEZ",
  "COLONIA": "BARRIO AZTLAN",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": 8127025581
 },
 {
  "SECCION CODG": 1100,
  "SECCION": 1100,
  "LETRA": "X",
  "EDAD": 55,
  "NOMBRE JUEZ": "BALDEMAR EDUARDO BENAVIDES VALDEZ",
  "COLONIA": "CHEPEVERA",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8116805595
 },
 {
  "SECCION CODG": 1014,
  "SECCION": 1014,
  "LETRA": "X",
  "EDAD": 53,
  "NOMBRE JUEZ": "BELINDA ANABELL GARZA MELO",
  "COLONIA": "BUROCRATAS FEDERALES",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8127543507
 },
 {
  "SECCION CODG": 1520,
  "SECCION": 1520,
  "LETRA": "X",
  "EDAD": 53,
  "NOMBRE JUEZ": "BERTHA ALICIA GONZALEZ GARCIA",
  "COLONIA": "23 DE MARZO",
  "SUPERVISOR ": "CLAUDIA ESPINOSA",
  "TELEFONOS DE CONTACTO": 8116527719
 },
 {
  "SECCION CODG": 2128,
  "SECCION": "2128-A",
  "LETRA": "A",
  "EDAD": 53,
  "NOMBRE JUEZ": "BLANCA ALICIA ESCOBEDO CASTRO",
  "COLONIA": "BARRIO SANTA ISABEL",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8117407471
 },
 {
  "SECCION CODG": 2126,
  "SECCION": "2126-C",
  "LETRA": "C",
  "EDAD": 51,
  "NOMBRE JUEZ": "BLANCA LILIA ZUÑIGA IRACHETA",
  "COLONIA": "MIRASOL 3 SEC",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": 8110620358
 },
 {
  "SECCION CODG": 1357,
  "SECCION": 1357,
  "LETRA": "X",
  "EDAD": 50,
  "NOMBRE JUEZ": "BLANCA MIREYA BRIAGAS MONTOYA",
  "COLONIA": "SIERRA VENTANA",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 8125409234
 },
 {
  "SECCION CODG": 1482,
  "SECCION": 1482,
  "LETRA": "X",
  "EDAD": 37,
  "NOMBRE JUEZ": "BRENDA JANETH RAMIREZ RANGEL",
  "COLONIA": "SAN BERNABE",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8110708843
 },
 {
  "SECCION CODG": 1285,
  "SECCION": 1285,
  "LETRA": "X",
  "EDAD": 51,
  "NOMBRE JUEZ": "BRIANA BETANCOURT ARRAMBIDE",
  "COLONIA": "CENTRO",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8116544168
 },
 {
  "SECCION CODG": 1596,
  "SECCION": 1596,
  "LETRA": "X",
  "EDAD": 52,
  "NOMBRE JUEZ": "CARLOS RODRIGUEZ GUTIERREZ",
  "COLONIA": "GRACIANO BORTONI",
  "SUPERVISOR ": "ELIZABETH ARELLANO",
  "TELEFONOS DE CONTACTO": 8116193266
 },
 {
  "SECCION CODG": 1687,
  "SECCION": 1687,
  "LETRA": "X",
  "EDAD": 32,
  "NOMBRE JUEZ": "CARMEN IDALIA PARDO TREVIÑO",
  "COLONIA": "ALAMOS DE CORREGIDORA",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8123066480
 },
 {
  "SECCION CODG": 1381,
  "SECCION": 1381,
  "LETRA": "X",
  "EDAD": 55,
  "NOMBRE JUEZ": "CECILIA TELLO PEREZ",
  "COLONIA": "LA CONDESA",
  "SUPERVISOR ": "CINTHIA TORRES",
  "TELEFONOS DE CONTACTO": 8129395965
 },
 {
  "SECCION CODG": 1390,
  "SECCION": 1390,
  "LETRA": "X",
  "EDAD": 54,
  "NOMBRE JUEZ": "CLAUDIA MARIA GUADALUPE POZO RIESTRA",
  "COLONIA": "VALLE DE LAS BRISAS",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 8110370139
 },
 {
  "SECCION CODG": 2130,
  "SECCION": "2130-A",
  "LETRA": "A",
  "EDAD": 44,
  "NOMBRE JUEZ": "CONSUELO EVANGELINA CERDA RAMIREZ",
  "COLONIA": "BARRIO ALAMEDA",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8180877198
 },
 {
  "SECCION CODG": 1662,
  "SECCION": "1662-1663",
  "LETRA": "X",
  "EDAD": 51,
  "NOMBRE JUEZ": "CRISTINA BARBOSA TREVIÑO",
  "COLONIA": "MODERNA",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8126114313
 },
 {
  "SECCION CODG": 1455,
  "SECCION": 1455,
  "LETRA": "X",
  "EDAD": 28,
  "NOMBRE JUEZ": "CRISTINA SARAHI ROCHA TRISTAN",
  "COLONIA": "GLORIA MENDIOLA",
  "SUPERVISOR ": "LILIANA REYNA",
  "TELEFONOS DE CONTACTO": 8131807564
 },
 {
  "SECCION CODG": 2134,
  "SECCION": "2134-B",
  "LETRA": "B",
  "EDAD": 37,
  "NOMBRE JUEZ": "DALIA LETICIA RAMIREZ ALVAREZ",
  "COLONIA": "BARRIO ESTRELLA",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8131411775
 },
 {
  "SECCION CODG": 1054,
  "SECCION": 1054,
  "LETRA": "X",
  "EDAD": 28,
  "NOMBRE JUEZ": "DALIA NALLELY MANRIQUEZ TREVIÑO",
  "COLONIA": "PROGRESO",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8124354182
 },
 {
  "SECCION CODG": 1463,
  "SECCION": 1463,
  "LETRA": "X",
  "EDAD": 66,
  "NOMBRE JUEZ": "DAMARIS ITZEL LERMA LLANES",
  "COLONIA": "MIRASOL 2 SEC",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": 8122954760
 },
 {
  "SECCION CODG": 1405,
  "SECCION": 1405,
  "LETRA": "X",
  "EDAD": 32,
  "NOMBRE JUEZ": "DANIEL ALEJANDRO JIMENEZ DIAZ",
  "COLONIA": "DEL PASEO RESIDENCIAL",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8112417486
 },
 {
  "SECCION CODG": 1421,
  "SECCION": 1421,
  "LETRA": "X",
  "EDAD": 46,
  "NOMBRE JUEZ": "DAVID EDUARDO RODRIGUEZ CASTILLO",
  "COLONIA": "FRACC. LOMAS DEL VERGEL",
  "SUPERVISOR ": "CINTHIA TORRES",
  "TELEFONOS DE CONTACTO": 5516833423
 },
 {
  "SECCION CODG": 1003,
  "SECCION": 1003,
  "LETRA": "X",
  "EDAD": 50,
  "NOMBRE JUEZ": "DAVID EDUARDO SILVESTRE GUAJARDO RODRIGUEZ",
  "COLONIA": "JARDIN DE LAS MITRAS",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8114667070
 },
 {
  "SECCION CODG": 1017,
  "SECCION": 1017,
  "LETRA": "X",
  "EDAD": 62,
  "NOMBRE JUEZ": "DIANA DE LA LUZ ESPINOSA GONZALEZ",
  "COLONIA": "MITRAS CENTRO",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8180889493
 },
 {
  "SECCION CODG": 1313,
  "SECCION": 1313,
  "LETRA": "X",
  "EDAD": 42,
  "NOMBRE JUEZ": "DIANA JOSEFINA HERNANDEZ COSTILLA",
  "COLONIA": "ALFONSO REYES",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 8114944515
 },
 {
  "SECCION CODG": 1629,
  "SECCION": "1629-1636-1639",
  "LETRA": "X",
  "EDAD": 58,
  "NOMBRE JUEZ": "DOLORES RAMIREZ GARCIA",
  "COLONIA": "NINO ARTILLERO",
  "SUPERVISOR ": "GUADALUPE ROCHA",
  "TELEFONOS DE CONTACTO": 8180162818
 },
 {
  "SECCION CODG": 1477,
  "SECCION": 1477,
  "LETRA": "X",
  "EDAD": 41,
  "NOMBRE JUEZ": "DORA ALICIA TOVAR MOLINA",
  "COLONIA": "FOMERREY 1",
  "SUPERVISOR ": "LILIANA REYNA",
  "TELEFONOS DE CONTACTO": "CASA 8134249098"
 },
 {
  "SECCION CODG": 1550,
  "SECCION": 1550,
  "LETRA": "X",
  "EDAD": 45,
  "NOMBRE JUEZ": "EFRAIN HERRERA ZAMARRON",
  "COLONIA": "TIERRA Y LIBERTAD",
  "SUPERVISOR ": "VIRIDIANA GONZALEZ",
  "TELEFONOS DE CONTACTO": 8110195899
 },
 {
  "SECCION CODG": 1453,
  "SECCION": 1453,
  "LETRA": "X",
  "EDAD": 64,
  "NOMBRE JUEZ": "ELIA SOTO CERDA",
  "COLONIA": "INFONAVIT SAN BERNABE",
  "SUPERVISOR ": "LILIANA REYNA",
  "TELEFONOS DE CONTACTO": 8114179495
 },
 {
  "SECCION CODG": 1634,
  "SECCION": 1634,
  "LETRA": "X",
  "EDAD": 68,
  "NOMBRE JUEZ": "ELISA CALDERON RODRIGUEZ",
  "COLONIA": "NINO ARTILLERO",
  "SUPERVISOR ": "GUADALUPE ROCHA",
  "TELEFONOS DE CONTACTO": 8126368832
 },
 {
  "SECCION CODG": 1426,
  "SECCION": 1426,
  "LETRA": "X",
  "EDAD": 46,
  "NOMBRE JUEZ": "EMILIA MARGARITA CARRANZA MARTINEZ",
  "COLONIA": "NOGALES DE LA SIERRA",
  "SUPERVISOR ": "CINTHIA TORRES",
  "TELEFONOS DE CONTACTO": 8112108160
 },
 {
  "SECCION CODG": 1425,
  "SECCION": "1425-B",
  "LETRA": "B",
  "EDAD": 23,
  "NOMBRE JUEZ": "ERIKA JANETH CAMACHO ESTRADA",
  "COLONIA": "VILLAS LA RIOJA",
  "SUPERVISOR ": "CINTHIA TORRES",
  "TELEFONOS DE CONTACTO": 8134176824
 },
 {
  "SECCION CODG": 1383,
  "SECCION": 1383,
  "LETRA": "X",
  "EDAD": 38,
  "NOMBRE JUEZ": "ERIKA MARLENE CASTRO LOPEZ",
  "COLONIA": "SAN ANGEL SUR",
  "SUPERVISOR ": "CINTHIA TORRES",
  "TELEFONOS DE CONTACTO": 8134485591
 },
 {
  "SECCION CODG": 1591,
  "SECCION": "1591-B",
  "LETRA": "B",
  "EDAD": 60,
  "NOMBRE JUEZ": "ESTELA CABRERA GONZALEZ",
  "COLONIA": "TIERRA Y LIBERTAD",
  "SUPERVISOR ": "VIRIDIANA GONZALEZ",
  "TELEFONOS DE CONTACTO": 8114848861
 },
 {
  "SECCION CODG": 1469,
  "SECCION": 1469,
  "LETRA": "X",
  "EDAD": 30,
  "NOMBRE JUEZ": "ESTEPHANY FRANCISCA GARCIA RODRIGUEZ",
  "COLONIA": "SAN BERNABE",
  "SUPERVISOR ": "LILIANA REYNA",
  "TELEFONOS DE CONTACTO": 8137758813
 },
 {
  "SECCION CODG": 1037,
  "SECCION": "1037-1038",
  "LETRA": "X",
  "EDAD": 69,
  "NOMBRE JUEZ": "ESTHER ALEMAN PATIÑO",
  "COLONIA": "EMILIANO ZAPATA",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8114755066
 },
 {
  "SECCION CODG": 1382,
  "SECCION": 1382,
  "LETRA": "X",
  "EDAD": 66,
  "NOMBRE JUEZ": "EUFRACIO DE JESUS UREÑA FRAUSTO",
  "COLONIA": "SAN ANGEL SUR",
  "SUPERVISOR ": "CINTHIA TORRES",
  "TELEFONOS DE CONTACTO": 8118114208
 },
 {
  "SECCION CODG": 1539,
  "SECCION": "1539-1597",
  "LETRA": "X",
  "EDAD": 23,
  "NOMBRE JUEZ": "EUNICE GABRIELA ROSALES PADRON",
  "COLONIA": "SAN JORGE",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8115018112
 },
 {
  "SECCION CODG": 1248,
  "SECCION": "1248-1249-1250",
  "LETRA": "X",
  "EDAD": 28,
  "NOMBRE JUEZ": "EUNICE MAGDALENA SOLIS CONTRERAS",
  "COLONIA": "MARTINEZ",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8182734836
 },
 {
  "SECCION CODG": 1214,
  "SECCION": "1214-1215-1216",
  "LETRA": "X",
  "EDAD": 49,
  "NOMBRE JUEZ": "EUSEBIO SANCHEZ PEREZ",
  "COLONIA": "INDEPENDENCIA",
  "SUPERVISOR ": "EDSON RANGEL",
  "TELEFONOS DE CONTACTO": 8125062984
 },
 {
  "SECCION CODG": 1624,
  "SECCION": 1624,
  "LETRA": "X",
  "EDAD": 54,
  "NOMBRE JUEZ": "EVANGELINA RODRIGUEZ ELIAS",
  "COLONIA": "TOPO CHICO",
  "SUPERVISOR ": "GUADALUPE ROCHA",
  "TELEFONOS DE CONTACTO": 8184682276
 },
 {
  "SECCION CODG": 1230,
  "SECCION": 1230,
  "LETRA": "X",
  "EDAD": 30,
  "NOMBRE JUEZ": "FABIOLA GUADALUPE ARGUELLO RODRIGUEZ",
  "COLONIA": "INDEPENDENCIA",
  "SUPERVISOR ": "EDSON RANGEL",
  "TELEFONOS DE CONTACTO": 8188682695
 },
 {
  "SECCION CODG": 1579,
  "SECCION": 1579,
  "LETRA": "X",
  "EDAD": 66,
  "NOMBRE JUEZ": "FERNANDO GALVEZ SANCHEZ",
  "COLONIA": "VILLA DORADA",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8110448322
 },
 {
  "SECCION CODG": 1461,
  "SECCION": 1461,
  "LETRA": "X",
  "EDAD": 54,
  "NOMBRE JUEZ": "FLORENCIA ORTA YERA",
  "COLONIA": "FOMERREY 115",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": 8126445361
 },
 {
  "SECCION CODG": 1108,
  "SECCION": "1108-1109",
  "LETRA": "X",
  "EDAD": 52,
  "NOMBRE JUEZ": "FRANCISCO ANIBAL GARZA CHAVEZ",
  "COLONIA": "CENTRO",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8181376920
 },
 {
  "SECCION CODG": 1623,
  "SECCION": 1623,
  "LETRA": "X",
  "EDAD": 71,
  "NOMBRE JUEZ": "FRANCISCO FERNANDO LOPEZ PEYRO",
  "COLONIA": "LOMAS DE ANAHUAC",
  "SUPERVISOR ": "GUADALUPE ROCHA",
  "TELEFONOS DE CONTACTO": 8186600223
 },
 {
  "SECCION CODG": 1511,
  "SECCION": 1511,
  "LETRA": "X",
  "EDAD": 56,
  "NOMBRE JUEZ": "FRANCISCO JAVIER GARCIA MARTINEZ",
  "COLONIA": "VALLE VERDE",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8181610902
 },
 {
  "SECCION CODG": 1470,
  "SECCION": 1470,
  "LETRA": "X",
  "EDAD": 25,
  "NOMBRE JUEZ": "FRANCISCO JAVIER TORRES ALVARADO",
  "COLONIA": "SAN BERNABE",
  "SUPERVISOR ": "LILIANA REYNA",
  "TELEFONOS DE CONTACTO": 8126583650
 },
 {
  "SECCION CODG": 1681,
  "SECCION": "1681-1682",
  "LETRA": "X",
  "EDAD": 60,
  "NOMBRE JUEZ": "GERARDO AGUILAR CHAGOYA",
  "COLONIA": "NUEVA MADERO",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8126116464
 },
 {
  "SECCION CODG": 1020,
  "SECCION": 1020,
  "LETRA": "X",
  "EDAD": 52,
  "NOMBRE JUEZ": "GINA MARTINEZ GONZALEZ",
  "COLONIA": "MITRAS CENTRO",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8115160271
 },
 {
  "SECCION CODG": 1127,
  "SECCION": 1127,
  "LETRA": "X",
  "EDAD": 63,
  "NOMBRE JUEZ": "GRACIELA GARCIA SOSA",
  "COLONIA": "PIO X",
  "SUPERVISOR ": "EDSON RANGEL",
  "TELEFONOS DE CONTACTO": 8111965146
 },
 {
  "SECCION CODG": 1244,
  "SECCION": "1244-1245-1246",
  "LETRA": "X",
  "EDAD": 55,
  "NOMBRE JUEZ": "GUADALUPE ALICIA GONZALEZ REYES",
  "COLONIA": "TERMINAL",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8111997387
 },
 {
  "SECCION CODG": 1240,
  "SECCION": 1240,
  "LETRA": "X",
  "EDAD": 53,
  "NOMBRE JUEZ": "GUADALUPE LEYVA BARRIENTOS",
  "COLONIA": "INDEPENDENCIA",
  "SUPERVISOR ": "EDSON RANGEL",
  "TELEFONOS DE CONTACTO": 8131074160
 },
 {
  "SECCION CODG": 1691,
  "SECCION": "1691-1692-1693",
  "LETRA": "X",
  "NOMBRE JUEZ": "GUADALUPE PRADO BERNAL",
  "COLONIA": "FRANCISCO I. MADERO",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8115003092
 },
 {
  "SECCION CODG": 1449,
  "SECCION": "1449-A",
  "LETRA": "A",
  "EDAD": 48,
  "NOMBRE JUEZ": "HERMELINDA SANCHEZ ESPINOSA",
  "COLONIA": "MIRASOL",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": 8127316815
 },
 {
  "SECCION CODG": 1350,
  "SECCION": 1350,
  "LETRA": "X",
  "NOMBRE JUEZ": "HILDA MARICELA VILLARREAL RODRIGUEZ",
  "COLONIA": "MAS PALOMAS",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": "8115133900 ó contacto Sra. Villarreal 8110808086"
 },
 {
  "SECCION CODG": 1625,
  "SECCION": 1625,
  "LETRA": "X",
  "EDAD": 66,
  "NOMBRE JUEZ": "HIPOLITO ALVAREZ JUAREZ",
  "COLONIA": "CONSTITUYENTES DEL 57",
  "SUPERVISOR ": "GUADALUPE ROCHA",
  "TELEFONOS DE CONTACTO": 8125934974
 },
 {
  "SECCION CODG": 1061,
  "SECCION": 1061,
  "LETRA": "X",
  "EDAD": 62,
  "NOMBRE JUEZ": "HORTENSIA IBARRA IBARRA",
  "COLONIA": "INDUSTRIAL",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8180228909
 },
 {
  "SECCION CODG": 1263,
  "SECCION": "1263-1264",
  "LETRA": "X",
  "EDAD": 51,
  "NOMBRE JUEZ": "ICELA DEL CARMEN AGUILAR OCHOA",
  "COLONIA": "CENTRO",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8181871480
 },
 {
  "SECCION CODG": 1674,
  "SECCION": 1674,
  "LETRA": "X",
  "EDAD": 51,
  "NOMBRE JUEZ": "IMELDA PEÑA RIVERA",
  "COLONIA": "MODERNA",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8138668185
 },
 {
  "SECCION CODG": 2130,
  "SECCION": "2130-B",
  "LETRA": "B",
  "EDAD": 44,
  "NOMBRE JUEZ": "INES GABRIELA DE LEON ARRIAGA",
  "COLONIA": "BARRIO DE SANTA ISABEL",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8184608987
 },
 {
  "SECCION CODG": 1613,
  "SECCION": 1613,
  "LETRA": "X",
  "EDAD": 33,
  "NOMBRE JUEZ": "IRANY VRISSETT VEGA SORIA",
  "COLONIA": "LAZARO CARDENAS",
  "SUPERVISOR ": "GUADALUPE ROCHA",
  "TELEFONOS DE CONTACTO": 8125975076
 },
 {
  "SECCION CODG": 1524,
  "SECCION": 1524,
  "LETRA": "X",
  "EDAD": 46,
  "NOMBRE JUEZ": "ISABEL CRISTINA TELLO MARTINEZ",
  "COLONIA": "VALLE DE SANTA LUCIA",
  "SUPERVISOR ": "CLAUDIA ESPINOSA",
  "TELEFONOS DE CONTACTO": 8134689873
 },
 {
  "SECCION CODG": 1366,
  "SECCION": 1366,
  "LETRA": "X",
  "EDAD": 18,
  "NOMBRE JUEZ": "ISIS GABRIEL CALDERON AGUILAR",
  "COLONIA": "ROMA",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8125631378
 },
 {
  "SECCION CODG": 1251,
  "SECCION": "1251-1252",
  "LETRA": "X",
  "EDAD": 37,
  "NOMBRE JUEZ": "JANETH IVON TORRES MENDEZ",
  "COLONIA": "TERMINAL",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8110635366
 },
 {
  "SECCION CODG": 2126,
  "SECCION": "2126-A",
  "LETRA": "A",
  "EDAD": 32,
  "NOMBRE JUEZ": "JAZMIN JANETH MARTINEZ PINEDA",
  "COLONIA": "NUEVA CONQUISTA",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": 8131761648
 },
 {
  "SECCION CODG": 1589,
  "SECCION": 1589,
  "LETRA": "X",
  "EDAD": 35,
  "NOMBRE JUEZ": "JENNIFER MARIA CORONADO FUENTES",
  "COLONIA": "CNOP",
  "SUPERVISOR ": "CLAUDIA ESPINOSA",
  "TELEFONOS DE CONTACTO": 8136332318
 },
 {
  "SECCION CODG": 1594,
  "SECCION": 1594,
  "LETRA": "X",
  "EDAD": 56,
  "NOMBRE JUEZ": "JESUS MANUEL LOZANO SANSABAS",
  "COLONIA": "16 DE SEPTIEMBRE",
  "SUPERVISOR ": "ELIZABETH ARELLANO",
  "TELEFONOS DE CONTACTO": 8123355835
 },
 {
  "SECCION CODG": 1499,
  "SECCION": 1499,
  "LETRA": "X",
  "EDAD": 61,
  "NOMBRE JUEZ": "JESUS SOLIS MORALES",
  "COLONIA": "FRANCISCO VILLA",
  "SUPERVISOR ": "CLAUDIA ESPINOSA",
  "TELEFONOS DE CONTACTO": 8114651208
 },
 {
  "SECCION CODG": 2133,
  "SECCION": "2133-C",
  "LETRA": "C",
  "EDAD": 42,
  "NOMBRE JUEZ": "JOHANA CAROLINA IRACHETA GONZALEZ",
  "COLONIA": "ESTRELLA",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8123404509
 },
 {
  "SECCION CODG": 1007,
  "SECCION": 1007,
  "LETRA": "X",
  "EDAD": 39,
  "NOMBRE JUEZ": "JORGE IVAN DEL ANGEL MONTEMAYOR",
  "COLONIA": "FRANCISCO GARCIA NARANJO (INDECO)",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8136224550
 },
 {
  "SECCION CODG": 1462,
  "SECCION": 1462,
  "LETRA": "X",
  "EDAD": 26,
  "NOMBRE JUEZ": "JOSE ALBERTO SALINAS ESPARZA",
  "COLONIA": "MIRASOL 2 SEC",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": "8123134200 o 8135963611"
 },
 {
  "SECCION CODG": 2134,
  "SECCION": "2134-D",
  "LETRA": "D",
  "EDAD": 56,
  "NOMBRE JUEZ": "JOSE ALFREDO RUIZ TORRES",
  "COLONIA": "BARRIO SAN CARLOS",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8112372158
 },
 {
  "SECCION CODG": 1519,
  "SECCION": "1519-A",
  "LETRA": "A",
  "EDAD": 80,
  "NOMBRE JUEZ": "JOSE ANGEL CASTILLO RENTERIA",
  "COLONIA": "7 DE NOVIEMBRE",
  "SUPERVISOR ": "CLAUDIA ESPINOSA",
  "TELEFONOS DE CONTACTO": 8110318199
 },
 {
  "SECCION CODG": 2129,
  "SECCION": "2129-B",
  "LETRA": "B",
  "EDAD": 51,
  "NOMBRE JUEZ": "JOSE CORDOVA CEDILLO",
  "COLONIA": "BARRIO SAN LUIS",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8117240307
 },
 {
  "SECCION CODG": 1337,
  "SECCION": 1337,
  "LETRA": "X",
  "EDAD": 18,
  "NOMBRE JUEZ": "JOSE EDUARDO HERRERA HERNANDEZ",
  "COLONIA": "ALTA VISTA",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 8125672204
 },
 {
  "SECCION CODG": 1326,
  "SECCION": 1326,
  "LETRA": "X",
  "EDAD": 38,
  "NOMBRE JUEZ": "JOSE ENRIQUE LARA CORTES",
  "COLONIA": "LA FLORIDA",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8110503686
 },
 {
  "SECCION CODG": 1481,
  "SECCION": 1481,
  "LETRA": "X",
  "EDAD": 59,
  "NOMBRE JUEZ": "JOSE FRANCISCO JAVIER AGUILAR CONTRERAS",
  "COLONIA": "SAN BERNABE ",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8137243926
 },
 {
  "SECCION CODG": 1374,
  "SECCION": 1374,
  "LETRA": "X",
  "EDAD": 35,
  "NOMBRE JUEZ": "JOSE FRANCISCO PUERTA MARTINEZ",
  "COLONIA": "ALFONSO REYES",
  "SUPERVISOR ": "EDSON RANGEL",
  "TELEFONOS DE CONTACTO": 8124235417
 },
 {
  "SECCION CODG": 1483,
  "SECCION": 1483,
  "LETRA": "X",
  "EDAD": 54,
  "NOMBRE JUEZ": "JOSE JUAN MARTINEZ CORREA",
  "COLONIA": "FOMERREY 51",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8116308312
 },
 {
  "SECCION CODG": "0987",
  "SECCION": 987,
  "LETRA": "X",
  "EDAD": 42,
  "NOMBRE JUEZ": "JOSE JULIAN ORTIZ FRAUSTO",
  "COLONIA": "SAN JOSE",
  "SUPERVISOR ": "VIRIDIANA GONZALEZ",
  "TELEFONOS DE CONTACTO": 8117640011
 },
 {
  "SECCION CODG": 1058,
  "SECCION": 1058,
  "LETRA": "X",
  "EDAD": 63,
  "NOMBRE JUEZ": "JOSE LEON CRUZ SAENZ",
  "COLONIA": "RUBEN JARAMILLO",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8126251995
 },
 {
  "SECCION CODG": 1023,
  "SECCION": 1023,
  "LETRA": "X",
  "EDAD": 65,
  "NOMBRE JUEZ": "JOSE MANUEL GONZALEZ RAMIREZ",
  "COLONIA": "PEDRO LOZANO",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8116918442
 },
 {
  "SECCION CODG": 1039,
  "SECCION": 1039,
  "LETRA": "X",
  "EDAD": 66,
  "NOMBRE JUEZ": "JOSE PASCUAL GUADALUPE RODRIGUEZ LAZARO",
  "COLONIA": "ZAPATA",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8112568367
 },
 {
  "SECCION CODG": 1397,
  "SECCION": 1397,
  "LETRA": "X",
  "EDAD": 55,
  "NOMBRE JUEZ": "JUAN BENIGNO MACARENO ARIAS",
  "COLONIA": "BUROCRATAS MUNICIPALES",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8117428003
 },
 {
  "SECCION CODG": 1540,
  "SECCION": 1540,
  "LETRA": "X",
  "EDAD": 60,
  "NOMBRE JUEZ": "JUAN CARLOS ESTRADA OLIVARES",
  "COLONIA": "VALLE VERDE",
  "SUPERVISOR ": "ELIZABETH ARELLANO",
  "TELEFONOS DE CONTACTO": 8112072897
 },
 {
  "SECCION CODG": 1473,
  "SECCION": 1473,
  "LETRA": "X",
  "EDAD": 56,
  "NOMBRE JUEZ": "JUAN JOSE DE LA ROSA XX",
  "COLONIA": "GLORIA MENDIOLA",
  "SUPERVISOR ": "LILIANA REYNA",
  "TELEFONOS DE CONTACTO": 8132485415
 },
 {
  "SECCION CODG": 1110,
  "SECCION": "1110-1111",
  "LETRA": "X",
  "EDAD": 49,
  "NOMBRE JUEZ": "JUAN MANUEL CANO VAZQUEZ",
  "COLONIA": "CENTRO",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8110240802
 },
 {
  "SECCION CODG": 1315,
  "SECCION": 1315,
  "LETRA": "X",
  "NOMBRE JUEZ": "JUAN MANUEL DE LA FUENTE GUTIERREZ",
  "COLONIA": "LA FLORIDA",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8123586524
 },
 {
  "SECCION CODG": 1627,
  "SECCION": 1627,
  "LETRA": "X",
  "EDAD": 30,
  "NOMBRE JUEZ": "JUANA INES MATA ESQUIVEL",
  "COLONIA": "HOGARES FERROCARRILEROS",
  "SUPERVISOR ": "GUADALUPE ROCHA",
  "TELEFONOS DE CONTACTO": 8139667560
 },
 {
  "SECCION CODG": 1434,
  "SECCION": 1434,
  "LETRA": "X",
  "EDAD": 53,
  "NOMBRE JUEZ": "JUANA MARIA HERNANDEZ GALVAN",
  "COLONIA": "FOMERREY 35",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": 8118257905
 },
 {
  "SECCION CODG": 1373,
  "SECCION": 1373,
  "LETRA": "X",
  "EDAD": 55,
  "NOMBRE JUEZ": "JUANA MARIA NAVARRETE RODRIGUEZ",
  "COLONIA": "ALTAMIRA",
  "SUPERVISOR ": "EDSON RANGEL",
  "TELEFONOS DE CONTACTO": 8115820050
 },
 {
  "SECCION CODG": 1384,
  "SECCION": 1384,
  "LETRA": "X",
  "EDAD": 49,
  "NOMBRE JUEZ": "JUANITA GUTIERREZ ELIZERIO",
  "COLONIA": "SAN ANGEL SUR",
  "SUPERVISOR ": "CINTHIA TORRES",
  "TELEFONOS DE CONTACTO": 8111060144
 },
 {
  "SECCION CODG": "0979",
  "SECCION": 979,
  "LETRA": "X",
  "EDAD": 45,
  "NOMBRE JUEZ": "JUANITA MIRASOL DE LEON PEREZ",
  "COLONIA": "FERROCARRILERA",
  "SUPERVISOR ": "VIRIDIANA GONZALEZ",
  "TELEFONOS DE CONTACTO": 8130822590
 },
 {
  "SECCION CODG": 1592,
  "SECCION": 1592,
  "LETRA": "X",
  "EDAD": 31,
  "NOMBRE JUEZ": "JULIA ABIGAIL GONZALEZ DURON",
  "COLONIA": "ANTIGUO FLORES MAGON",
  "SUPERVISOR ": "VIRIDIANA GONZALEZ",
  "TELEFONOS DE CONTACTO": 8116082453
 },
 {
  "SECCION CODG": 1385,
  "SECCION": 1385,
  "LETRA": "X",
  "EDAD": 34,
  "NOMBRE JUEZ": "JULIA CAROLINA CHAPA RAMOS",
  "COLONIA": "LOS REMATES",
  "SUPERVISOR ": "CINTHIA TORRES",
  "TELEFONOS DE CONTACTO": 8133954613
 },
 {
  "SECCION CODG": 1048,
  "SECCION": "1048-1049",
  "LETRA": "X",
  "EDAD": 72,
  "NOMBRE JUEZ": "JULIETA PISANTY MARIN",
  "COLONIA": "LEONES",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8119993432
 },
 {
  "SECCION CODG": 1424,
  "SECCION": 1424,
  "LETRA": "X",
  "EDAD": 28,
  "NOMBRE JUEZ": "KARINA GUADALUPE ORTIZ HORTA",
  "COLONIA": "FOMERREY 45",
  "SUPERVISOR ": "CINTHIA TORRES",
  "TELEFONOS DE CONTACTO": 8130991443
 },
 {
  "SECCION CODG": 1620,
  "SECCION": "1620-1621",
  "LETRA": "X",
  "EDAD": 41,
  "NOMBRE JUEZ": "KARLA MAYELA CHABOYA CISNEROS",
  "COLONIA": "TOPO CHICO",
  "SUPERVISOR ": "GUADALUPE ROCHA",
  "TELEFONOS DE CONTACTO": 8183766913
 },
 {
  "SECCION CODG": 1553,
  "SECCION": 1553,
  "LETRA": "X",
  "EDAD": 35,
  "NOMBRE JUEZ": "KARLA NATALY MENDEZ CORDOVA",
  "COLONIA": "FRANCISCO GONZALEZ BOCANEGRA",
  "SUPERVISOR ": "CLAUDIA ESPINOSA",
  "TELEFONOS DE CONTACTO": 8140511183
 },
 {
  "SECCION CODG": 1508,
  "SECCION": 1508,
  "LETRA": "X",
  "EDAD": 27,
  "NOMBRE JUEZ": "KATIA MARISOL VAZQUEZ HERNANDEZ",
  "COLONIA": "HACIENDA MITRAS",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8128592048
 },
 {
  "SECCION CODG": 1079,
  "SECCION": "1079-1103-1104",
  "LETRA": "X",
  "NOMBRE JUEZ": "LAURA CARDONA RODRIGUEZ",
  "COLONIA": "CENTRO",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": "8114530177 ó 8128776934"
 },
 {
  "SECCION CODG": 1367,
  "SECCION": 1367,
  "LETRA": "X",
  "EDAD": 47,
  "NOMBRE JUEZ": "LAURA PATRICIA MIRANDA GARCIA",
  "COLONIA": "FRACCIONAMIENTO CENTRO",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8182533981
 },
 {
  "SECCION CODG": 1537,
  "SECCION": "1537-1570",
  "LETRA": "X",
  "EDAD": 70,
  "NOMBRE JUEZ": "LILIA HERRERA CORTES",
  "COLONIA": "VALLE DE INF 3E",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8116901470
 },
 {
  "SECCION CODG": 2124,
  "SECCION": "2124-F",
  "LETRA": "F",
  "EDAD": 31,
  "NOMBRE JUEZ": "LILIANA ABIGAIL HINOJOSA PEREZ",
  "COLONIA": "PERIODISTAS DE MEXICO",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8110304304
 },
 {
  "SECCION CODG": 1505,
  "SECCION": 1505,
  "LETRA": "X",
  "EDAD": 35,
  "NOMBRE JUEZ": "LINDA BRISEL AGUERO SANCHEZ",
  "COLONIA": "FIDEL VELAZQUEZ ",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8125943773
 },
 {
  "SECCION CODG": 1153,
  "SECCION": "1153-1154",
  "LETRA": "X",
  "EDAD": 36,
  "NOMBRE JUEZ": "LUCIA GABRIELA GARZA AGUIRRE",
  "COLONIA": "OBRERISTA",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8135643554
 },
 {
  "SECCION CODG": 1064,
  "SECCION": 1064,
  "LETRA": "X",
  "EDAD": 54,
  "NOMBRE JUEZ": "LUCIA GUADALUPE MARTINEZ HUERTA",
  "COLONIA": "10 DE MARZO",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8136065920
 },
 {
  "SECCION CODG": 1446,
  "SECCION": 1446,
  "LETRA": "X",
  "EDAD": 69,
  "NOMBRE JUEZ": "LUCINA RIVERA REYES",
  "COLONIA": "EL PORVENIR",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": 8132622744
 },
 {
  "SECCION CODG": 2132,
  "SECCION": "2132-A",
  "LETRA": "A",
  "EDAD": 47,
  "NOMBRE JUEZ": "LUDIVINA RAMOS NAVARRO",
  "COLONIA": "LA ALIANZA",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8134326485
 },
 {
  "SECCION CODG": 2124,
  "SECCION": "2124-C",
  "LETRA": "C",
  "EDAD": 42,
  "NOMBRE JUEZ": "MA ADRIANA CORONADO VIGIL",
  "COLONIA": "ROMULO LOZANO",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8125911781
 },
 {
  "SECCION CODG": 1379,
  "SECCION": 1379,
  "LETRA": "X",
  "EDAD": 57,
  "NOMBRE JUEZ": "MA ELIZABETH GONZALEZ AMAYA",
  "COLONIA": "SIERRA VENTANA",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 8184674243
 },
 {
  "SECCION CODG": 1562,
  "SECCION": 1562,
  "LETRA": "X",
  "NOMBRE JUEZ": "MA ESTELA MARROQUIN MARROQUIN",
  "COLONIA": "VALLE DE SANTA CECILIA",
  "SUPERVISOR ": "ELIZABETH ARELLANO",
  "TELEFONOS DE CONTACTO": 8124657924
 },
 {
  "SECCION CODG": 1585,
  "SECCION": 1585,
  "LETRA": "X",
  "EDAD": 63,
  "NOMBRE JUEZ": "MA GUADALUPE GARCIA RODRIGUEZ",
  "COLONIA": "LOMAS MODELO NTE",
  "SUPERVISOR ": "ELIZABETH ARELLANO",
  "TELEFONOS DE CONTACTO": 8124025352
 },
 {
  "SECCION CODG": 1517,
  "SECCION": 1517,
  "LETRA": "X",
  "EDAD": 62,
  "NOMBRE JUEZ": "MA. DE JESUS SANCHEZ MARTINEZ",
  "COLONIA": "VALLE DE SANTA LUCIA",
  "SUPERVISOR ": "CLAUDIA ESPINOSA",
  "TELEFONOS DE CONTACTO": 8121098275
 },
 {
  "SECCION CODG": 1289,
  "SECCION": "1289-1290",
  "LETRA": "X",
  "NOMBRE JUEZ": "MA. GUADALUPE GARCIA ROSALES",
  "COLONIA": "NUEVO REPUEBLO",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8112795404
 },
 {
  "SECCION CODG": 1331,
  "SECCION": 1331,
  "LETRA": "X",
  "EDAD": 70,
  "NOMBRE JUEZ": "MAGDA ESTHER TREVIÑO FERNANDEZ",
  "COLONIA": "PRIMAVERA PLAYA",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 8117902228
 },
 {
  "SECCION CODG": 1522,
  "SECCION": 1522,
  "LETRA": "X",
  "EDAD": 39,
  "NOMBRE JUEZ": "MAGDA NELLY PIÑA GONZALEZ",
  "COLONIA": "SAN ANGEL (FOMERREY 78)",
  "SUPERVISOR ": "CLAUDIA ESPINOSA",
  "TELEFONOS DE CONTACTO": 8113258774
 },
 {
  "SECCION CODG": 1549,
  "SECCION": 1549,
  "LETRA": "X",
  "EDAD": 30,
  "NOMBRE JUEZ": "MAGDALENA DE LA CRUZ DEL ANGEL",
  "COLONIA": "UNIDAD DEL PUEBLO",
  "SUPERVISOR ": "VIRIDIANA GONZALEZ",
  "TELEFONOS DE CONTACTO": 8124153091
 },
 {
  "SECCION CODG": 1431,
  "SECCION": 1431,
  "LETRA": "X",
  "EDAD": 64,
  "NOMBRE JUEZ": "MARCELINA REYNOSO TELLEZ",
  "COLONIA": "LAS JARAS",
  "SUPERVISOR ": "CINTHIA TORRES",
  "TELEFONOS DE CONTACTO": 8111777570
 },
 {
  "SECCION CODG": 1073,
  "SECCION": 1073,
  "LETRA": "X",
  "EDAD": 44,
  "NOMBRE JUEZ": "MARCO ANTONIO HERNANDEZ SANCHEZ",
  "COLONIA": "TIJERINA",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8125021111
 },
 {
  "SECCION CODG": 1006,
  "SECCION": 1006,
  "LETRA": "X",
  "EDAD": 49,
  "NOMBRE JUEZ": "MARGARITA BALDERAS VARGAS",
  "COLONIA": "FRANCISCO GARCIA NARANJO (INDECO)",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8130919150
 },
 {
  "SECCION CODG": 1371,
  "SECCION": 1371,
  "LETRA": "X",
  "EDAD": 53,
  "NOMBRE JUEZ": "MARIA AMELIA TOVAR MORIN",
  "COLONIA": "ALFONSO REYES",
  "SUPERVISOR ": "EDSON RANGEL",
  "TELEFONOS DE CONTACTO": 8126908848
 },
 {
  "SECCION CODG": 1476,
  "SECCION": 1476,
  "LETRA": "X",
  "EDAD": 52,
  "NOMBRE JUEZ": "MARIA ANA DE JESUS MENDOZA AMAYA",
  "COLONIA": "LIBERTADORES DE AMERICA",
  "SUPERVISOR ": "LILIANA REYNA",
  "TELEFONOS DE CONTACTO": 8116848059
 },
 {
  "SECCION CODG": 1231,
  "SECCION": 1231,
  "LETRA": "X",
  "EDAD": 53,
  "NOMBRE JUEZ": "MARIA ANTONIA MIGUEL ALMAGUER",
  "COLONIA": "INDEPENDENCIA",
  "SUPERVISOR ": "EDSON RANGEL",
  "TELEFONOS DE CONTACTO": 8110741715
 },
 {
  "SECCION CODG": 1159,
  "SECCION": "1159-1160-1161",
  "LETRA": "X",
  "EDAD": 59,
  "NOMBRE JUEZ": "MARIA ANTONIA SANCHEZ RUBIO",
  "COLONIA": "INDUSTRIAL",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8131139513
 },
 {
  "SECCION CODG": 1409,
  "SECCION": 1409,
  "LETRA": "X",
  "EDAD": 64,
  "NOMBRE JUEZ": "MARIA ARIELA CERVANTES RAMIREZ",
  "COLONIA": "LA REPUBLICA",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8121829497
 },
 {
  "SECCION CODG": 1651,
  "SECCION": "1651-1652",
  "LETRA": "X",
  "EDAD": 44,
  "NOMBRE JUEZ": "MARIA CATALINA GARCIA BUSTOS",
  "COLONIA": "VIDRIERA",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8130577461
 },
 {
  "SECCION CODG": 1475,
  "SECCION": 1475,
  "LETRA": "X",
  "EDAD": 41,
  "NOMBRE JUEZ": "MARIA DE JESUS GOMEZ CELEDON",
  "COLONIA": "RENE ALVAREZ",
  "SUPERVISOR ": "LILIANA REYNA",
  "TELEFONOS DE CONTACTO": 8116898501
 },
 {
  "SECCION CODG": "0999",
  "SECCION": 999,
  "LETRA": "X",
  "EDAD": 46,
  "NOMBRE JUEZ": "MARIA DE JESUS GUADALUPE HERNANDEZ SIGALA",
  "COLONIA": "ESTRELLA",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8125978182
 },
 {
  "SECCION CODG": 1642,
  "SECCION": 1642,
  "LETRA": "X",
  "EDAD": 65,
  "NOMBRE JUEZ": "MARIA DE LA PAZ MONJARAZ DE LA CRUZ",
  "COLONIA": "RESIDENCIAL VIDRIERA",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8116598289
 },
 {
  "SECCION CODG": 1489,
  "SECCION": 1489,
  "LETRA": "X",
  "EDAD": 60,
  "NOMBRE JUEZ": "MARIA DE LOURDES ARZOLA MARTINEZ",
  "COLONIA": "PLUTARCO ELIAS",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8115310552
 },
 {
  "SECCION CODG": 1659,
  "SECCION": 1659,
  "LETRA": "X",
  "EDAD": 63,
  "NOMBRE JUEZ": "MARIA DE LOURDES CORONA VAZQUEZ",
  "COLONIA": "MODERNA",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8110511362
 },
 {
  "SECCION CODG": 1513,
  "SECCION": 1513,
  "LETRA": "X",
  "EDAD": 62,
  "NOMBRE JUEZ": "MARIA DEL CARMEN COVARRUBIAS XX",
  "COLONIA": "PASO DEL AGUILA",
  "SUPERVISOR ": "ELIZABETH ARELLANO",
  "TELEFONOS DE CONTACTO": 8183105567
 },
 {
  "SECCION CODG": 1370,
  "SECCION": 1370,
  "LETRA": "X",
  "NOMBRE JUEZ": "MARIA DEL CARMEN MIRANDA RAMIREZ",
  "COLONIA": "ALFONSO REYES",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8120278356
 },
 {
  "SECCION CODG": 1028,
  "SECCION": 1028,
  "LETRA": "X",
  "NOMBRE JUEZ": "MARIA DEL CARMEN VILLARREAL RIOS",
  "COLONIA": "BELLA VISTA",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8123462110
 },
 {
  "SECCION CODG": 1631,
  "SECCION": "1631-1633",
  "LETRA": "X",
  "EDAD": 34,
  "NOMBRE JUEZ": "MARIA DEL CONSUELO ONTIVEROS SAUCEDO",
  "COLONIA": "LUIS ECHEVERRIA",
  "SUPERVISOR ": "GUADALUPE ROCHA",
  "TELEFONOS DE CONTACTO": 8119904935
 },
 {
  "SECCION CODG": 1493,
  "SECCION": 1493,
  "LETRA": "X",
  "EDAD": 63,
  "NOMBRE JUEZ": "MARIA DEL REFUGIO SANCHEZ HERNANDEZ",
  "COLONIA": "SAN BERNABE",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8110519631
 },
 {
  "SECCION CODG": 1614,
  "SECCION": "1614-1615",
  "LETRA": "X",
  "EDAD": 44,
  "NOMBRE JUEZ": "MARIA DEL REFUGIO SANTIBAÑEZ VELEZ",
  "COLONIA": "TOPO CHICO",
  "SUPERVISOR ": "GUADALUPE ROCHA",
  "TELEFONOS DE CONTACTO": 8116201876
 },
 {
  "SECCION CODG": 1480,
  "SECCION": 1480,
  "LETRA": "X",
  "EDAD": 53,
  "NOMBRE JUEZ": "MARIA DEL SOCORRO CAMPOS MARQUEZ",
  "COLONIA": "SAN BERNABE",
  "SUPERVISOR ": "LILIANA REYNA",
  "TELEFONOS DE CONTACTO": 8125626266
 },
 {
  "SECCION CODG": 1452,
  "SECCION": 1452,
  "LETRA": "X",
  "EDAD": 35,
  "NOMBRE JUEZ": "MARIA DEL SOCORRO GUERRERO GAMEZ",
  "COLONIA": "SAN BERNABE (FOMERREY 112)",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": 8124351966
 },
 {
  "SECCION CODG": 1496,
  "SECCION": 1496,
  "LETRA": "X",
  "EDAD": 62,
  "NOMBRE JUEZ": "MARIA DOLORES ESPINOSA CARDONA",
  "COLONIA": "SAN MARTIN",
  "SUPERVISOR ": "CLAUDIA ESPINOSA",
  "TELEFONOS DE CONTACTO": 8115011166
 },
 {
  "SECCION CODG": 1353,
  "SECCION": 1353,
  "LETRA": "X",
  "EDAD": 42,
  "NOMBRE JUEZ": "MARIA DOLORES PEREZ DE LARA SEPULVEDA",
  "COLONIA": "JARDINES DEL CONTRY",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 8112031834
 },
 {
  "SECCION CODG": 1024,
  "SECCION": 1024,
  "LETRA": "X",
  "EDAD": 49,
  "NOMBRE JUEZ": "MARIA EDNA PINALES CERVANTES",
  "COLONIA": "GARZA NIETO",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8182082696
 },
 {
  "SECCION CODG": 1360,
  "SECCION": 1360,
  "LETRA": "X",
  "NOMBRE JUEZ": "MARIA ELENA GUZMAN CONTRERAS",
  "COLONIA": "BALCONES DE ALTA VISTA",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8123586524
 },
 {
  "SECCION CODG": 1679,
  "SECCION": "1679-1680",
  "LETRA": "X",
  "EDAD": 52,
  "NOMBRE JUEZ": "MARIA ELENA HERNANDEZ MARTINEZ",
  "COLONIA": "ARGENTINA",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8133999379
 },
 {
  "SECCION CODG": 1362,
  "SECCION": "1362-1363",
  "LETRA": "X",
  "EDAD": 57,
  "NOMBRE JUEZ": "MARIA ELENA PEREZ CHAVARRIA",
  "COLONIA": "CERRO DE LA CAMPANA",
  "SUPERVISOR ": "EDSON RANGEL",
  "TELEFONOS DE CONTACTO": 8125351964
 },
 {
  "SECCION CODG": 1368,
  "SECCION": 1368,
  "LETRA": "X",
  "EDAD": 68,
  "NOMBRE JUEZ": "MARIA EMMA GARCIA RODARTE",
  "COLONIA": "FRACCIONAMIENTO INDEPENDENCIA ",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8183878611
 },
 {
  "SECCION CODG": 1425,
  "SECCION": "1425-C",
  "LETRA": "C",
  "EDAD": 56,
  "NOMBRE JUEZ": "MARIA ESTHER ARRIAGA IBARRA",
  "COLONIA": "NOGALES DE LA SIERRA",
  "SUPERVISOR ": "CINTHIA TORRES",
  "TELEFONOS DE CONTACTO": 8136204456
 },
 {
  "SECCION CODG": 1394,
  "SECCION": 1394,
  "LETRA": "X",
  "EDAD": 52,
  "NOMBRE JUEZ": "MARIA ESTHER MARTINEZ PEÑA",
  "COLONIA": "VALLE DEL MARQUEZ",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8114827570
 },
 {
  "SECCION CODG": 1257,
  "SECCION": "1257-1261",
  "LETRA": "X",
  "EDAD": 29,
  "NOMBRE JUEZ": "MARIA FERNANDA PEREZ FALCON",
  "COLONIA": "TERMINAL",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8129158318
 },
 {
  "SECCION CODG": 1053,
  "SECCION": "1053-1068",
  "LETRA": "X",
  "EDAD": 61,
  "NOMBRE JUEZ": "MARIA ISABEL MORALES LOZANO",
  "COLONIA": "PROGRESO",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8123217861
 },
 {
  "SECCION CODG": 1458,
  "SECCION": 1458,
  "LETRA": "X",
  "EDAD": 57,
  "NOMBRE JUEZ": "MARIA ISABEL VILLEGAS BLANCO",
  "COLONIA": "FOMERREY 114",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": 8180896543
 },
 {
  "SECCION CODG": 1358,
  "SECCION": 1358,
  "LETRA": "X",
  "EDAD": 36,
  "NOMBRE JUEZ": "MARIA JOSEFINA GAMEZ RIOS",
  "COLONIA": "REVOLUCION PROLETARIA",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 8126631680
 },
 {
  "SECCION CODG": 2717,
  "SECCION": "2717-2799-2800-2801",
  "LETRA": "X",
  "EDAD": 57,
  "NOMBRE JUEZ": "MARIA LETICIA RODRIGUEZ GARCIA",
  "COLONIA": "CUMBRES LA JOYA",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8127591585
 },
 {
  "SECCION CODG": 1658,
  "SECCION": "1658-1675",
  "LETRA": "X",
  "EDAD": 67,
  "NOMBRE JUEZ": "MARIA LUISA ALONSO PALACIOS",
  "COLONIA": "MODERNA",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8183540813
 },
 {
  "SECCION CODG": 1542,
  "SECCION": 1542,
  "LETRA": "X",
  "EDAD": 71,
  "NOMBRE JUEZ": "MARIA LUISA HERNANDEZ DE HOYOS",
  "COLONIA": "UNIDAD MODELO",
  "SUPERVISOR ": "ELIZABETH ARELLANO",
  "TELEFONOS DE CONTACTO": 8182051385
 },
 {
  "SECCION CODG": 1495,
  "SECCION": 1495,
  "LETRA": "X",
  "EDAD": 28,
  "NOMBRE JUEZ": "MARIA TERESA DELGADO CEJA",
  "COLONIA": "SAN BERNABE",
  "SUPERVISOR ": "LILIANA REYNA",
  "TELEFONOS DE CONTACTO": 8183817007
 },
 {
  "SECCION CODG": "0989",
  "SECCION": 989,
  "LETRA": "X",
  "EDAD": 71,
  "NOMBRE JUEZ": "MARIA TERESA GUERRA REYES",
  "COLONIA": "CENTRAL",
  "SUPERVISOR ": "VIRIDIANA GONZALEZ",
  "TELEFONOS DE CONTACTO": 8119029922
 },
 {
  "SECCION CODG": 1168,
  "SECCION": "1168-1173-1174-1175-1176-1177",
  "LETRA": "X",
  "EDAD": 51,
  "NOMBRE JUEZ": "MARIA TERESA VILLARREAL ELIZONDO",
  "COLONIA": "CENTRO",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8123929020
 },
 {
  "SECCION CODG": 1560,
  "SECCION": 1560,
  "LETRA": "X",
  "EDAD": 31,
  "NOMBRE JUEZ": "MARIO ALBERTO MARTINEZ MORIN",
  "COLONIA": "BARRIO PUERTA DEL SOL",
  "SUPERVISOR ": "ELIZABETH ARELLANO",
  "TELEFONOS DE CONTACTO": 8124323139
 },
 {
  "SECCION": "1448-A",
  "LETRA": "A",
  "NOMBRE JUEZ": "MARIO HERNANDEZ MENDOZA",
  "COLONIA": "MODERNA",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": 8181875710
 },
 {
  "SECCION CODG": 1561,
  "SECCION": 1561,
  "LETRA": "X",
  "EDAD": 33,
  "NOMBRE JUEZ": "MARISOL HERNANDEZ ESPINO",
  "COLONIA": "GENARO VAZQUEZ",
  "SUPERVISOR ": "ELIZABETH ARELLANO",
  "TELEFONOS DE CONTACTO": 8117070461
 },
 {
  "SECCION CODG": "0980",
  "SECCION": 980,
  "LETRA": "X",
  "EDAD": 52,
  "NOMBRE JUEZ": "MARTHA ALICIA PUENTE GONZALEZ",
  "COLONIA": "FERROCARRILERA",
  "SUPERVISOR ": "VIRIDIANA GONZALEZ",
  "TELEFONOS DE CONTACTO": 8112443688
 },
 {
  "SECCION CODG": 1492,
  "SECCION": 1492,
  "LETRA": "X",
  "EDAD": 62,
  "NOMBRE JUEZ": "MARTHA ELVIA ZAVALA SANCHEZ",
  "COLONIA": "PLUTARCO ELIAS",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8110728457
 },
 {
  "SECCION CODG": 1124,
  "SECCION": "1124-A",
  "LETRA": "A",
  "EDAD": 65,
  "NOMBRE JUEZ": "MARTHA LOPEZ ZARATE",
  "COLONIA": "INDEPENDENCIA",
  "SUPERVISOR ": "EDSON RANGEL",
  "TELEFONOS DE CONTACTO": 8123633319
 },
 {
  "SECCION CODG": 1301,
  "SECCION": "1301-1304",
  "LETRA": "X",
  "EDAD": 55,
  "NOMBRE JUEZ": "MAURILIO LOPEZ NUNCIO",
  "COLONIA": "LA FLORIDA",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8182773660
 },
 {
  "SECCION CODG": 1030,
  "SECCION": 1030,
  "LETRA": "X",
  "EDAD": 45,
  "NOMBRE JUEZ": "MAYRA ALICIA PALOMO HERNANDEZ",
  "COLONIA": "BENITO JUAREZ",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8132706589
 },
 {
  "SECCION CODG": 1467,
  "SECCION": 1467,
  "LETRA": "X",
  "EDAD": 28,
  "NOMBRE JUEZ": "MELANIE PATRICIA MERAZ SIERRA",
  "COLONIA": "SAN BERNABE",
  "SUPERVISOR ": "LILIANA REYNA",
  "TELEFONOS DE CONTACTO": 8131359954
 },
 {
  "SECCION CODG": 1569,
  "SECCION": 1569,
  "LETRA": "X",
  "EDAD": 59,
  "NOMBRE JUEZ": "MINERVA RUGERIO GUTIERREZ",
  "COLONIA": "VALLE VERDE",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8119881814
 },
 {
  "SECCION CODG": 1060,
  "SECCION": 1060,
  "LETRA": "X",
  "EDAD": 44,
  "NOMBRE JUEZ": "MIRIAM DOLORES DEGOLLADO GARCIA",
  "COLONIA": "INDUSTRIAL",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8115832539
 },
 {
  "SECCION CODG": 1518,
  "SECCION": 1518,
  "LETRA": "X",
  "EDAD": 47,
  "NOMBRE JUEZ": "MIRTHALA MENDEZ DE LA ROSA",
  "COLONIA": "FRANCISCO VILLA",
  "SUPERVISOR ": "CLAUDIA ESPINOSA",
  "TELEFONOS DE CONTACTO": 8131004784
 },
 {
  "SECCION CODG": 1437,
  "SECCION": 1437,
  "LETRA": "X",
  "EDAD": 48,
  "NOMBRE JUEZ": "MONICA SALDAÑA HERNANDEZ",
  "COLONIA": "FOMERREY 24",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": 8135666012
 },
 {
  "SECCION CODG": 1220,
  "SECCION": "1220-1221-1223",
  "LETRA": "X",
  "EDAD": 34,
  "NOMBRE JUEZ": "NANCY ANGELICA HERNANDEZ ESQUIVEL",
  "COLONIA": "INDEPENDENCIA",
  "SUPERVISOR ": "EDSON RANGEL",
  "TELEFONOS DE CONTACTO": 8115627953
 },
 {
  "SECCION CODG": 1032,
  "SECCION": 1032,
  "LETRA": "X",
  "EDAD": 50,
  "NOMBRE JUEZ": "NELIDA LEAL ROJAS",
  "COLONIA": "BENITO JUAREZ",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8130443210
 },
 {
  "SECCION CODG": 2124,
  "SECCION": "2124-J",
  "LETRA": "J",
  "EDAD": 50,
  "NOMBRE JUEZ": "NOE JUAN CORONA SALDAÑA",
  "COLONIA": "LA ALIANZA",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8117975295
 },
 {
  "SECCION CODG": 1617,
  "SECCION": 1617,
  "LETRA": "X",
  "EDAD": 44,
  "NOMBRE JUEZ": "NOELIA SANCHEZ BUSTOS",
  "COLONIA": "4 DE DICIEMBRE",
  "SUPERVISOR ": "VIRIDIANA GONZALEZ",
  "TELEFONOS DE CONTACTO": 8124199788
 },
 {
  "SECCION CODG": 1500,
  "SECCION": 1500,
  "LETRA": "X",
  "EDAD": 25,
  "NOMBRE JUEZ": "NOHEMI DEYANIRA PADILLA CANO",
  "COLONIA": "VALLE DE SANTA LUCIA",
  "SUPERVISOR ": "CLAUDIA ESPINOSA",
  "TELEFONOS DE CONTACTO": 8111162771
 },
 {
  "SECCION CODG": 1533,
  "SECCION": 1533,
  "LETRA": "X",
  "EDAD": 62,
  "NOMBRE JUEZ": "NORA ANGELICA MENDOZA ESPINOSA",
  "COLONIA": "HDA MITRAS",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8123790983
 },
 {
  "SECCION CODG": 1490,
  "SECCION": 1490,
  "LETRA": "X",
  "EDAD": 38,
  "NOMBRE JUEZ": "NORMA ALVARADO PINALES",
  "COLONIA": "PLUTARCO ELIAS",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8114888811
 },
 {
  "SECCION CODG": 1380,
  "SECCION": 1380,
  "LETRA": "X",
  "EDAD": 49,
  "NOMBRE JUEZ": "OLGA NELLY RANGEL GONZALEZ",
  "COLONIA": "LAS BRISAS",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 8119823956
 },
 {
  "SECCION CODG": 1312,
  "SECCION": 1312,
  "LETRA": "X",
  "EDAD": 61,
  "NOMBRE JUEZ": "PABLO ROBERTO CANTU GALVAN",
  "COLONIA": "RESIDENCIAL LA ESPANOLA",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8182877233
 },
 {
  "SECCION CODG": 1567,
  "SECCION": 1567,
  "LETRA": "X",
  "EDAD": 56,
  "NOMBRE JUEZ": "PATRICIA MIRELES BRICEÑO",
  "COLONIA": "VALLE VERDE",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8120242863
 },
 {
  "SECCION CODG": 1074,
  "SECCION": 1074,
  "LETRA": "X",
  "EDAD": 56,
  "NOMBRE JUEZ": "PATRICIA RAMIREZ CORONADO",
  "COLONIA": "TALLERES",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8110397429
 },
 {
  "SECCION CODG": 1258,
  "SECCION": "1258-1259-1260",
  "LETRA": "X",
  "EDAD": 27,
  "NOMBRE JUEZ": "PRISCILA VANESSA CAMPOS LEAL",
  "COLONIA": "PABLO A DE LA GARZA",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8115837751
 },
 {
  "SECCION CODG": 1335,
  "SECCION": 1335,
  "LETRA": "X",
  "EDAD": 72,
  "NOMBRE JUEZ": "RAMON URBANO PIÑA LIZARRAGA",
  "COLONIA": "VALLE DE LA PRIMAVERA",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 8183596586
 },
 {
  "SECCION CODG": 1628,
  "SECCION": 1628,
  "LETRA": "X",
  "EDAD": 55,
  "NOMBRE JUEZ": "RAMONA ALVAREZ GARCIA",
  "COLONIA": "HOGARES FERROCARRILEROS",
  "SUPERVISOR ": "GUADALUPE ROCHA",
  "TELEFONOS DE CONTACTO": 8186533043
 },
 {
  "SECCION CODG": 1619,
  "SECCION": 1619,
  "LETRA": "X",
  "EDAD": 40,
  "NOMBRE JUEZ": "RAQUEL CASTILLO ESCALONA",
  "COLONIA": "TOPO CHICO",
  "SUPERVISOR ": "GUADALUPE ROCHA",
  "TELEFONOS DE CONTACTO": 8125281424
 },
 {
  "SECCION CODG": 1449,
  "SECCION": "1449-B",
  "LETRA": "B",
  "EDAD": 67,
  "NOMBRE JUEZ": "RAYMUNDO LLANES RODRIGUEZ",
  "COLONIA": "MIRASOL",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": 8134004693
 },
 {
  "SECCION CODG": 1435,
  "SECCION": 1435,
  "LETRA": "X",
  "EDAD": 54,
  "NOMBRE JUEZ": "REBECA NIETO MARTINEZ",
  "COLONIA": "CONQUISTADORES",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": 8124077071
 },
 {
  "SECCION CODG": 1330,
  "SECCION": 1330,
  "LETRA": "X",
  "EDAD": 69,
  "NOMBRE JUEZ": "REDUCINDO MENDOZA GONZALEZ",
  "COLONIA": "LA PRIMAVERA",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 8186766216
 },
 {
  "SECCION CODG": 1478,
  "SECCION": 1478,
  "LETRA": "X",
  "EDAD": 64,
  "NOMBRE JUEZ": "RENE ESTALA CORONADO",
  "COLONIA": "FOMERREY 1",
  "SUPERVISOR ": "LILIANA REYNA",
  "TELEFONOS DE CONTACTO": 8115446598
 },
 {
  "SECCION CODG": 1688,
  "SECCION": "1688-1689-1690",
  "LETRA": "X",
  "EDAD": 18,
  "NOMBRE JUEZ": "REYNA ELIZABETH MARTINEZ DELGADO",
  "COLONIA": "FRANCISCO I. MADERO",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8133914412
 },
 {
  "SECCION CODG": 1400,
  "SECCION": "1400-B",
  "LETRA": "B",
  "EDAD": 48,
  "NOMBRE JUEZ": "REYNA IBARRA JASSO",
  "COLONIA": "ALTAMIRA",
  "SUPERVISOR ": "EDSON RANGEL",
  "TELEFONOS DE CONTACTO": 8129307084
 },
 {
  "SECCION CODG": 1376,
  "SECCION": 1376,
  "LETRA": "X",
  "EDAD": 33,
  "NOMBRE JUEZ": "RICARDO MONCADA RODRIGUEZ",
  "COLONIA": "LOS ROSALES",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8117429693
 },
 {
  "SECCION CODG": 1096,
  "SECCION": "1096-B",
  "LETRA": "B",
  "EDAD": 36,
  "NOMBRE JUEZ": "ROBERTO ADRIAN ALEJO GARZA",
  "COLONIA": "SAN JERONIMO",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8121211731
 },
 {
  "SECCION CODG": 1178,
  "SECCION": "1178-1180-1181",
  "LETRA": "X",
  "EDAD": 29,
  "NOMBRE JUEZ": "ROBERTO ALVISO MARQUES",
  "COLONIA": "CENTRO",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8112773785
 },
 {
  "SECCION CODG": 1328,
  "SECCION": "1328-1329",
  "LETRA": "X",
  "EDAD": 67,
  "NOMBRE JUEZ": "ROBERTO GALLARDO ARBALLO",
  "COLONIA": "ESTADIO",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 8135555227
 },
 {
  "SECCION CODG": 1667,
  "SECCION": 1667,
  "LETRA": "X",
  "EDAD": 66,
  "NOMBRE JUEZ": "ROBERTO SUAREZ ACOSTA",
  "COLONIA": "REFORMA",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8134969984
 },
 {
  "SECCION CODG": 1316,
  "SECCION": 1316,
  "LETRA": "X",
  "EDAD": 37,
  "NOMBRE JUEZ": "ROCIO ANGELICA GONZALEZ CORTES",
  "COLONIA": "LA FLORIDA",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8181366490
 },
 {
  "SECCION CODG": 1065,
  "SECCION": 1065,
  "LETRA": "X",
  "EDAD": 46,
  "NOMBRE JUEZ": "ROCIO ELIZABETH SALAZAR DELGADO",
  "COLONIA": "10 DE MARZO",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8113143710
 },
 {
  "SECCION CODG": 1233,
  "SECCION": 1233,
  "LETRA": "X",
  "EDAD": 57,
  "NOMBRE JUEZ": "RODOLFO MORENO AGUILAR",
  "COLONIA": "INDEPENDENCIA",
  "SUPERVISOR ": "EDSON RANGEL",
  "TELEFONOS DE CONTACTO": 8116725603
 },
 {
  "SECCION CODG": 1234,
  "SECCION": "1234-1235",
  "LETRA": "X",
  "EDAD": 35,
  "NOMBRE JUEZ": "ROSA ALEJANDRA RODRIGUEZ MENDEZ",
  "COLONIA": "INDEPENDENCIA",
  "SUPERVISOR ": "EDSON RANGEL",
  "TELEFONOS DE CONTACTO": 8113223184
 },
 {
  "SECCION CODG": 1351,
  "SECCION": 1351,
  "LETRA": "X",
  "EDAD": 63,
  "NOMBRE JUEZ": "ROSA IMELDA VELAZQUEZ FRANCO",
  "COLONIA": "MAS PALOMAS",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 8116333171
 },
 {
  "SECCION CODG": 1392,
  "SECCION": 1392,
  "LETRA": "X",
  "EDAD": 48,
  "NOMBRE JUEZ": "ROSA MARIA HINOJOSA AGUIRRE",
  "COLONIA": "VALLE DE LAS BRISAS",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8115395881
 },
 {
  "SECCION CODG": 1472,
  "SECCION": 1472,
  "LETRA": "X",
  "EDAD": 68,
  "NOMBRE JUEZ": "ROSENDO CARRASCO REYES",
  "COLONIA": "SAN BERNABE",
  "SUPERVISOR ": "LILIANA REYNA",
  "TELEFONOS DE CONTACTO": 8187043908
 },
 {
  "SECCION CODG": "0984",
  "SECCION": 984,
  "LETRA": "X",
  "EDAD": 44,
  "NOMBRE JUEZ": "RUTH MARTINEZ XX",
  "COLONIA": "FERROCARRILERA",
  "SUPERVISOR ": "VIRIDIANA GONZALEZ",
  "TELEFONOS DE CONTACTO": 8110157960
 },
 {
  "SECCION CODG": 1044,
  "SECCION": 1044,
  "LETRA": "X",
  "EDAD": 64,
  "NOMBRE JUEZ": "SALVADOR LEAL PAUL",
  "COLONIA": "CUMBRES 2 SECTOR",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8180197054
 },
 {
  "SECCION CODG": 1603,
  "SECCION": 1603,
  "LETRA": "X",
  "EDAD": 46,
  "NOMBRE JUEZ": "SANDRA EDITH LOPEZ IRACHETA",
  "COLONIA": "LOS ALTOS",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8132499315
 },
 {
  "SECCION CODG": 1412,
  "SECCION": 1412,
  "LETRA": "X",
  "EDAD": 39,
  "NOMBRE JUEZ": "SANDRA NELLY ESQUIVEL FLORES",
  "COLONIA": "VILLASOL",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8180215311
 },
 {
  "SECCION CODG": 1566,
  "SECCION": 1566,
  "LETRA": "X",
  "EDAD": 46,
  "NOMBRE JUEZ": "SANDRA VERONICA DE LA CRUZ GAYTAN",
  "COLONIA": "VALLE DE SANTA CECILIA",
  "SUPERVISOR ": "ELIZABETH ARELLANO",
  "TELEFONOS DE CONTACTO": 8123716244
 },
 {
  "SECCION CODG": 2129,
  "SECCION": "2129-C",
  "LETRA": "C",
  "EDAD": 44,
  "NOMBRE JUEZ": "SARA EUNICE LERMA SANCHEZ",
  "COLONIA": "ARCOS DEL SOL",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8123836310
 },
 {
  "SECCION CODG": 1095,
  "SECCION": 1095,
  "LETRA": "X",
  "EDAD": 56,
  "NOMBRE JUEZ": "SARA MARGARITA TORRES SANTOS",
  "COLONIA": "SAN JERONIMO",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8115551977
 },
 {
  "SECCION CODG": 1521,
  "SECCION": 1521,
  "LETRA": "X",
  "EDAD": 38,
  "NOMBRE JUEZ": "SAUL IVAN CHIHUAHUA LUNA",
  "COLONIA": "FOMERREY 106",
  "SUPERVISOR ": "CLAUDIA ESPINOSA",
  "TELEFONOS DE CONTACTO": 8184732630
 },
 {
  "SECCION CODG": 2131,
  "SECCION": "2131-B",
  "LETRA": "B",
  "EDAD": 47,
  "NOMBRE JUEZ": "SELENE YADIRA GARZA ESTRADA",
  "COLONIA": "BARRIO ALAMEDA",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8180150055
 },
 {
  "SECCION CODG": 1318,
  "SECCION": 1318,
  "LETRA": "X",
  "EDAD": 64,
  "NOMBRE JUEZ": "SILVANO SALAZAR NAVA",
  "COLONIA": "LA FLORIDA",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8183157379
 },
 {
  "SECCION CODG": 1422,
  "SECCION": "1422-B",
  "LETRA": "B",
  "EDAD": 51,
  "NOMBRE JUEZ": "SILVIA CORONA CASTILLON",
  "COLONIA": "RESIDENCIAL LA LAGRIMA",
  "SUPERVISOR ": "CINTHIA TORRES",
  "TELEFONOS DE CONTACTO": 8112986166
 },
 {
  "SECCION CODG": 1334,
  "SECCION": 1334,
  "LETRA": "X",
  "EDAD": 55,
  "NOMBRE JUEZ": "SILVIA NELLY HERNANDEZ HERNANDEZ",
  "COLONIA": "CONTRY",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 8110114649
 },
 {
  "SECCION CODG": 1598,
  "SECCION": 1598,
  "LETRA": "X",
  "EDAD": 41,
  "NOMBRE JUEZ": "SUSANA AIDE YATTES ALVARADO",
  "COLONIA": "LOS CEDROS",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8117911419
 },
 {
  "SECCION CODG": 1375,
  "SECCION": "1375-A",
  "LETRA": "A",
  "EDAD": 62,
  "NOMBRE JUEZ": "TERESA DE JESUS DIAZ OLVERA",
  "COLONIA": "BUROCRATAS MUNICIPALES",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8182531253
 },
 {
  "SECCION CODG": 1671,
  "SECCION": "1671-1672",
  "LETRA": "X",
  "EDAD": 51,
  "NOMBRE JUEZ": "TERESA DEL ROBLE ESTRADA CISNEROS",
  "COLONIA": "MODERNA",
  "SUPERVISOR ": "DARIO MEJIA",
  "TELEFONOS DE CONTACTO": 8113772598
 },
 {
  "SECCION CODG": 1454,
  "SECCION": 1454,
  "LETRA": "X",
  "EDAD": 37,
  "NOMBRE JUEZ": "TERESA ESMERALDA SALAZAR ALVARADO",
  "COLONIA": "EL PROVENIR",
  "SUPERVISOR ": "LILIANA REYNA",
  "TELEFONOS DE CONTACTO": 8124391110
 },
 {
  "SECCION CODG": 1055,
  "SECCION": "1055-1056-1057",
  "LETRA": "X",
  "EDAD": 68,
  "NOMBRE JUEZ": "URBANO SALAZAR ORTIZ",
  "COLONIA": "PROGRESO",
  "SUPERVISOR ": "JESUS FLORES MORALES",
  "TELEFONOS DE CONTACTO": 8111777306
 },
 {
  "SECCION CODG": 1396,
  "SECCION": 1396,
  "LETRA": "X",
  "EDAD": 53,
  "NOMBRE JUEZ": "VERONICA LUNA LOPEZ",
  "COLONIA": "VALPARAISO",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8110107177
 },
 {
  "SECCION CODG": 1365,
  "SECCION": 1365,
  "LETRA": "X",
  "EDAD": 49,
  "NOMBRE JUEZ": "VICTOR ENRIQUE CEPEDA ALANIS",
  "COLONIA": "ROMA",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8112770183
 },
 {
  "SECCION CODG": 1464,
  "SECCION": "1464-1465",
  "LETRA": "X",
  "EDAD": 41,
  "NOMBRE JUEZ": "VICTOR HUGO VELAZQUEZ HERNANDEZ",
  "COLONIA": "FOMERREY 109",
  "SUPERVISOR ": "-",
  "TELEFONOS DE CONTACTO": 8116739776
 },
 {
  "SECCION CODG": 1005,
  "SECCION": 1005,
  "LETRA": "X",
  "EDAD": 54,
  "NOMBRE JUEZ": "VICTOR MANUEL BAENA RODRIGUEZ",
  "COLONIA": "VALLE DE LAS MITRAS",
  "SUPERVISOR ": "GIOVANNA PEREZ",
  "TELEFONOS DE CONTACTO": 8134447507
 },
 {
  "SECCION CODG": 1451,
  "SECCION": 1451,
  "LETRA": "X",
  "EDAD": 62,
  "NOMBRE JUEZ": "VICTOR MANUEL GALLEGOS",
  "COLONIA": "SAN BERNABE (FOMERREY 112)",
  "SUPERVISOR ": "ISMAEL SILVA",
  "TELEFONOS DE CONTACTO": 8132492908
 },
 {
  "SECCION CODG": 1402,
  "SECCION": 1402,
  "LETRA": "X",
  "EDAD": 58,
  "NOMBRE JUEZ": "VIRGINIA RAMOS PEREZ",
  "COLONIA": "VALLE DEL MIRADOR",
  "SUPERVISOR ": "TERESA BOLAÑOS",
  "TELEFONOS DE CONTACTO": 8112106712
 },
 {
  "SECCION CODG": 1295,
  "SECCION": "1295-1296-2725",
  "LETRA": "X",
  "EDAD": 46,
  "NOMBRE JUEZ": "XIOMARA YAZMIN HERNANDEZ PINEDA",
  "COLONIA": "BUENOS AIRES",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8186579558
 },
 {
  "SECCION CODG": 1355,
  "SECCION": 1355,
  "LETRA": "X",
  "EDAD": 35,
  "NOMBRE JUEZ": "YAHAIRA YESENIA JUAREZ ARANDA",
  "COLONIA": "SIERRA VENTANA",
  "SUPERVISOR ": "ISELA URIBE",
  "TELEFONOS DE CONTACTO": 8123792222
 },
 {
  "SECCION CODG": 2134,
  "SECCION": "2134-C",
  "LETRA": "C",
  "EDAD": 44,
  "NOMBRE JUEZ": "YESIKA GRACIELA LEAÑOS GARCIA",
  "COLONIA": "BARRIO SAN CARLOS",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8119101482
 },
 {
  "SECCION CODG": 2133,
  "SECCION": "2133-A",
  "LETRA": "A",
  "EDAD": 29,
  "NOMBRE JUEZ": "YOKABETH GUEL ALONSO",
  "COLONIA": "LA ALIANZA",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8113874745
 },
 {
  "SECCION CODG": 1698,
  "SECCION": "1698-1699",
  "LETRA": "X",
  "EDAD": 60,
  "NOMBRE JUEZ": "YOLANDA MARICELA TAMAYO GARCIA",
  "COLONIA": "FRANCISCO I. MADERO",
  "SUPERVISOR ": "SOFIA MERAZ",
  "TELEFONOS DE CONTACTO": 8124009155
 },
 {
  "SECCION CODG": 1590,
  "SECCION": 1590,
  "LETRA": "X",
  "EDAD": 33,
  "NOMBRE JUEZ": "YULIANA BERENICE ALEMAN SEGURA",
  "COLONIA": "TIERRA Y LIBERTAD",
  "SUPERVISOR ": "VIRIDIANA GONZALEZ",
  "TELEFONOS DE CONTACTO": 8128650154
 },
 {
  "SECCION CODG": 2124,
  "SECCION": "2124-D",
  "LETRA": "D",
  "EDAD": 22,
  "NOMBRE JUEZ": "ZAIRA YARELLY CALVILLO GONZALEZ",
  "COLONIA": "LA ALIANZA",
  "SUPERVISOR ": "JUAN CASTILLO",
  "TELEFONOS DE CONTACTO": 8125025091
 }
],
"Hoja1":[
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "AGRIPINA SOLEDAD NAVA HERNANDEZ",
  "NARVARTE": "VALLE DEL TOPO CHICO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ALEJANDRO JAVIER DE LEON REYNA",
  "NARVARTE": "LOMA LINDA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ALEJANDRO MANUEL SALINAS GARZA",
  "NARVARTE": "SAN BERNABE XV SECTOR (FOMERREY 110)"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ALMA ESTHER AYALA ESTRADA",
  "NARVARTE": "SAN ANGEL SUR"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ALMA ESTHER RODRIGUEZ CASTAÑEDA",
  "NARVARTE": "REAL CUMBRES"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ALMA RUT CASTILLO HERNANDEZ",
  "NARVARTE": "MARIANO ESCOBEDO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ALMA VIOLETA IÑIGUEZ TORRES",
  "NARVARTE": "TALLERES"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ANA GABRIELA PAGAZA OJEDA",
  "NARVARTE": "LOMAS DE ANAHUAC"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ANA LAURA CHAVEZ ORTEGA",
  "NARVARTE": "MITRAS CENTRO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ANDRES ZUÑIGA SEGURA",
  "NARVARTE": "LOMAS DE SANTA CECILIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ANGELICA MARIA SALAS HERRERA",
  "NARVARTE": "TANQUES DE GUADALUPE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ARMANDINA RODRIGUEZ HERRERA",
  "NARVARTE": "DEL PASEO RESIDENCIAL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ARMANDO ISRAEL SANCHEZ MARTINEZ",
  "NARVARTE": "BARRIO AZTLAN"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "BALDEMAR EDUARDO BENAVIDES VALDEZ",
  "NARVARTE": "CHEPEVERA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "BELINDA ANABELL GARZA MELO",
  "NARVARTE": "BUROCRATAS FEDERALES"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "BERTHA ALICIA GONZALEZ GARCIA",
  "NARVARTE": "23 DE MARZO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "BLANCA ALICIA ESCOBEDO CASTRO",
  "NARVARTE": "BARRIO SANTA ISABEL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "BLANCA LILIA ZUÑIGA IRACHETA",
  "NARVARTE": "MIRASOL 3 SEC"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "BLANCA MIREYA BRIAGAS MONTOYA",
  "NARVARTE": "SIERRA VENTANA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "BRENDA JANETH RAMIREZ RANGEL",
  "NARVARTE": "SAN BERNABE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "BRIANA BETANCOURT ARRAMBIDE",
  "NARVARTE": "CENTRO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "CARLOS RODRIGUEZ GUTIERREZ",
  "NARVARTE": "GRACIANO BORTONI"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "CARMEN IDALIA PARDO TREVIÑO",
  "NARVARTE": "ALAMOS DE CORREGIDORA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "CECILIA TELLO PEREZ",
  "NARVARTE": "LA CONDESA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "CLAUDIA MARIA GUADALUPE POZO RIESTRA",
  "NARVARTE": "VALLE DE LAS BRISAS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "CONSUELO EVANGELINA CERDA RAMIREZ",
  "NARVARTE": "BARRIO ALAMEDA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "CRISTINA BARBOSA TREVIÑO",
  "NARVARTE": "MODERNA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "CRISTINA SARAHI ROCHA TRISTAN",
  "NARVARTE": "GLORIA MENDIOLA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "DALIA LETICIA RAMIREZ ALVAREZ",
  "NARVARTE": "BARRIO ESTRELLA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "DALIA NALLELY MANRIQUEZ TREVIÑO",
  "NARVARTE": "PROGRESO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "DAMARIS ITZEL LERMA LLANES",
  "NARVARTE": "MIRASOL 2 SEC"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "DANIEL ALEJANDRO JIMENEZ DIAZ",
  "NARVARTE": "DEL PASEO RESIDENCIAL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "DAVID EDUARDO RODRIGUEZ CASTILLO",
  "NARVARTE": "FRACC. LOMAS DEL VERGEL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "DAVID EDUARDO SILVESTRE GUAJARDO RODRIGUEZ",
  "NARVARTE": "JARDIN DE LAS MITRAS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "DIANA DE LA LUZ ESPINOSA GONZALEZ",
  "NARVARTE": "MITRAS CENTRO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "DIANA JOSEFINA HERNANDEZ COSTILLA",
  "NARVARTE": "ALFONSO REYES"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "DOLORES RAMIREZ GARCIA",
  "NARVARTE": "NINO ARTILLERO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "DORA ALICIA TOVAR MOLINA",
  "NARVARTE": "FOMERREY 1"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "EFRAIN HERRERA ZAMARRON",
  "NARVARTE": "TIERRA Y LIBERTAD"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ELIA SOTO CERDA",
  "NARVARTE": "INFONAVIT SAN BERNABE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ELISA CALDERON RODRIGUEZ",
  "NARVARTE": "NINO ARTILLERO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "EMILIA MARGARITA CARRANZA MARTINEZ",
  "NARVARTE": "NOGALES DE LA SIERRA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ERIKA JANETH CAMACHO ESTRADA",
  "NARVARTE": "VILLAS LA RIOJA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ERIKA MARLENE CASTRO LOPEZ",
  "NARVARTE": "SAN ANGEL SUR"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ESTELA CABRERA GONZALEZ",
  "NARVARTE": "TIERRA Y LIBERTAD"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ESTEPHANY FRANCISCA GARCIA RODRIGUEZ",
  "NARVARTE": "SAN BERNABE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ESTHER ALEMAN PATIÑO",
  "NARVARTE": "EMILIANO ZAPATA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "EUFRACIO DE JESUS UREÑA FRAUSTO",
  "NARVARTE": "SAN ANGEL SUR"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "EUNICE GABRIELA ROSALES PADRON",
  "NARVARTE": "SAN JORGE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "EUNICE MAGDALENA SOLIS CONTRERAS",
  "NARVARTE": "MARTINEZ"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "EUSEBIO SANCHEZ PEREZ",
  "NARVARTE": "INDEPENDENCIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "EVANGELINA RODRIGUEZ ELIAS",
  "NARVARTE": "TOPO CHICO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "FABIOLA GUADALUPE ARGUELLO RODRIGUEZ",
  "NARVARTE": "INDEPENDENCIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "FERNANDO GALVEZ SANCHEZ",
  "NARVARTE": "VILLA DORADA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "FLORENCIA ORTA YERA",
  "NARVARTE": "FOMERREY 115"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "FRANCISCO ANIBAL GARZA CHAVEZ",
  "NARVARTE": "CENTRO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "FRANCISCO FERNANDO LOPEZ PEYRO",
  "NARVARTE": "LOMAS DE ANAHUAC"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "FRANCISCO JAVIER GARCIA MARTINEZ",
  "NARVARTE": "VALLE VERDE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "FRANCISCO JAVIER TORRES ALVARADO",
  "NARVARTE": "SAN BERNABE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "GERARDO AGUILAR CHAGOYA",
  "NARVARTE": "NUEVA MADERO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "GINA MARTINEZ GONZALEZ",
  "NARVARTE": "MITRAS CENTRO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "GRACIELA GARCIA SOSA",
  "NARVARTE": "PIO X"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "GUADALUPE ALICIA GONZALEZ REYES",
  "NARVARTE": "TERMINAL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "GUADALUPE LEYVA BARRIENTOS",
  "NARVARTE": "INDEPENDENCIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "GUADALUPE PRADO BERNAL",
  "NARVARTE": "FRANCISCO I. MADERO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "HERMELINDA SANCHEZ ESPINOSA",
  "NARVARTE": "MIRASOL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "HILDA MARICELA VILLARREAL RODRIGUEZ",
  "NARVARTE": "MAS PALOMAS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "HIPOLITO ALVAREZ JUAREZ",
  "NARVARTE": "CONSTITUYENTES DEL 57"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "HORTENSIA IBARRA IBARRA",
  "NARVARTE": "INDUSTRIAL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ICELA DEL CARMEN AGUILAR OCHOA",
  "NARVARTE": "CENTRO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "IMELDA PEÑA RIVERA",
  "NARVARTE": "MODERNA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "INES GABRIELA DE LEON ARRIAGA",
  "NARVARTE": "BARRIO DE SANTA ISABEL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "IRANY VRISSETT VEGA SORIA",
  "NARVARTE": "LAZARO CARDENAS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ISABEL CRISTINA TELLO MARTINEZ",
  "NARVARTE": "VALLE DE SANTA LUCIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ISIS GABRIEL CALDERON AGUILAR",
  "NARVARTE": "ROMA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JANETH IVON TORRES MENDEZ",
  "NARVARTE": "TERMINAL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JAZMIN JANETH MARTINEZ PINEDA",
  "NARVARTE": "NUEVA CONQUISTA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JENNIFER MARIA CORONADO FUENTES",
  "NARVARTE": "CNOP"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JESUS MANUEL LOZANO SANSABAS",
  "NARVARTE": "16 DE SEPTIEMBRE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JESUS SOLIS MORALES",
  "NARVARTE": "FRANCISCO VILLA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JOHANA CAROLINA IRACHETA GONZALEZ",
  "NARVARTE": "ESTRELLA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JORGE IVAN DEL ANGEL MONTEMAYOR",
  "NARVARTE": "FRANCISCO GARCIA NARANJO (INDECO)"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JOSE ALBERTO SALINAS ESPARZA",
  "NARVARTE": "MIRASOL 2 SEC"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JOSE ALFREDO RUIZ TORRES",
  "NARVARTE": "BARRIO SAN CARLOS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JOSE ANGEL CASTILLO RENTERIA",
  "NARVARTE": "7 DE NOVIEMBRE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JOSE CORDOVA CEDILLO",
  "NARVARTE": "BARRIO SAN LUIS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JOSE EDUARDO HERRERA HERNANDEZ",
  "NARVARTE": "ALTA VISTA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JOSE ENRIQUE LARA CORTES",
  "NARVARTE": "LA FLORIDA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JOSE FRANCISCO JAVIER AGUILAR CONTRERAS",
  "NARVARTE": "SAN BERNABE "
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JOSE FRANCISCO PUERTA MARTINEZ",
  "NARVARTE": "ALFONSO REYES"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JOSE JUAN MARTINEZ CORREA",
  "NARVARTE": "FOMERREY 51"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JOSE JULIAN ORTIZ FRAUSTO",
  "NARVARTE": "SAN JOSE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JOSE LEON CRUZ SAENZ",
  "NARVARTE": "RUBEN JARAMILLO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JOSE MANUEL GONZALEZ RAMIREZ",
  "NARVARTE": "PEDRO LOZANO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JOSE PASCUAL GUADALUPE RODRIGUEZ LAZARO",
  "NARVARTE": "ZAPATA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JUAN BENIGNO MACARENO ARIAS",
  "NARVARTE": "BUROCRATAS MUNICIPALES"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JUAN CARLOS ESTRADA OLIVARES",
  "NARVARTE": "VALLE VERDE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JUAN JOSE DE LA ROSA XX",
  "NARVARTE": "GLORIA MENDIOLA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JUAN MANUEL CANO VAZQUEZ",
  "NARVARTE": "CENTRO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JUAN MANUEL DE LA FUENTE GUTIERREZ",
  "NARVARTE": "LA FLORIDA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JUANA INES MATA ESQUIVEL",
  "NARVARTE": "HOGARES FERROCARRILEROS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JUANA MARIA HERNANDEZ GALVAN",
  "NARVARTE": "FOMERREY 35"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JUANA MARIA NAVARRETE RODRIGUEZ",
  "NARVARTE": "ALTAMIRA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JUANITA GUTIERREZ ELIZERIO",
  "NARVARTE": "SAN ANGEL SUR"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JUANITA MIRASOL DE LEON PEREZ",
  "NARVARTE": "FERROCARRILERA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JULIA ABIGAIL GONZALEZ DURON",
  "NARVARTE": "ANTIGUO FLORES MAGON"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JULIA CAROLINA CHAPA RAMOS",
  "NARVARTE": "LOS REMATES"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "JULIETA PISANTY MARIN",
  "NARVARTE": "LEONES"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "KARINA GUADALUPE ORTIZ HORTA",
  "NARVARTE": "FOMERREY 45"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "KARLA MAYELA CHABOYA CISNEROS",
  "NARVARTE": "TOPO CHICO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "KARLA NATALY MENDEZ CORDOVA",
  "NARVARTE": "FRANCISCO GONZALEZ BOCANEGRA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "KATIA MARISOL VAZQUEZ HERNANDEZ",
  "NARVARTE": "HACIENDA MITRAS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "LAURA CARDONA RODRIGUEZ",
  "NARVARTE": "CENTRO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "LAURA PATRICIA MIRANDA GARCIA",
  "NARVARTE": "FRACCIONAMIENTO CENTRO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "LILIA HERRERA CORTES",
  "NARVARTE": "VALLE DE INF 3E"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "LILIANA ABIGAIL HINOJOSA PEREZ",
  "NARVARTE": "PERIODISTAS DE MEXICO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "LINDA BRISEL AGUERO SANCHEZ",
  "NARVARTE": "FIDEL VELAZQUEZ "
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "LUCIA GABRIELA GARZA AGUIRRE",
  "NARVARTE": "OBRERISTA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "LUCIA GUADALUPE MARTINEZ HUERTA",
  "NARVARTE": "10 DE MARZO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "LUCINA RIVERA REYES",
  "NARVARTE": "EL PORVENIR"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "LUDIVINA RAMOS NAVARRO",
  "NARVARTE": "LA ALIANZA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MA ADRIANA CORONADO VIGIL",
  "NARVARTE": "ROMULO LOZANO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MA ELIZABETH GONZALEZ AMAYA",
  "NARVARTE": "SIERRA VENTANA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MA ESTELA MARROQUIN MARROQUIN",
  "NARVARTE": "VALLE DE SANTA CECILIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MA GUADALUPE GARCIA RODRIGUEZ",
  "NARVARTE": "LOMAS MODELO NTE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MA. DE JESUS SANCHEZ MARTINEZ",
  "NARVARTE": "VALLE DE SANTA LUCIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MA. GUADALUPE GARCIA ROSALES",
  "NARVARTE": "NUEVO REPUEBLO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MAGDA ESTHER TREVIÑO FERNANDEZ",
  "NARVARTE": "PRIMAVERA PLAYA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MAGDA NELLY PIÑA GONZALEZ",
  "NARVARTE": "SAN ANGEL (FOMERREY 78)"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MAGDALENA DE LA CRUZ DEL ANGEL",
  "NARVARTE": "UNIDAD DEL PUEBLO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARCELINA REYNOSO TELLEZ",
  "NARVARTE": "LAS JARAS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARCO ANTONIO HERNANDEZ SANCHEZ",
  "NARVARTE": "TIJERINA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARGARITA BALDERAS VARGAS",
  "NARVARTE": "FRANCISCO GARCIA NARANJO (INDECO)"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA AMELIA TOVAR MORIN",
  "NARVARTE": "ALFONSO REYES"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA ANA DE JESUS MENDOZA AMAYA",
  "NARVARTE": "LIBERTADORES DE AMERICA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA ANTONIA MIGUEL ALMAGUER",
  "NARVARTE": "INDEPENDENCIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA ANTONIA SANCHEZ RUBIO",
  "NARVARTE": "INDUSTRIAL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA ARIELA CERVANTES RAMIREZ",
  "NARVARTE": "LA REPUBLICA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA CATALINA GARCIA BUSTOS",
  "NARVARTE": "VIDRIERA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA DE JESUS GOMEZ CELEDON",
  "NARVARTE": "RENE ALVAREZ"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA DE JESUS GUADALUPE HERNANDEZ SIGALA",
  "NARVARTE": "ESTRELLA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA DE LA PAZ MONJARAZ DE LA CRUZ",
  "NARVARTE": "RESIDENCIAL VIDRIERA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA DE LOURDES ARZOLA MARTINEZ",
  "NARVARTE": "PLUTARCO ELIAS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA DE LOURDES CORONA VAZQUEZ",
  "NARVARTE": "MODERNA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA DEL CARMEN COVARRUBIAS XX",
  "NARVARTE": "PASO DEL AGUILA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA DEL CARMEN MIRANDA RAMIREZ",
  "NARVARTE": "ALFONSO REYES"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA DEL CARMEN VILLARREAL RIOS",
  "NARVARTE": "BELLA VISTA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA DEL CONSUELO ONTIVEROS SAUCEDO",
  "NARVARTE": "LUIS ECHEVERRIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA DEL REFUGIO SANCHEZ HERNANDEZ",
  "NARVARTE": "SAN BERNABE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA DEL REFUGIO SANTIBAÑEZ VELEZ",
  "NARVARTE": "TOPO CHICO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA DEL SOCORRO CAMPOS MARQUEZ",
  "NARVARTE": "SAN BERNABE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA DEL SOCORRO GUERRERO GAMEZ",
  "NARVARTE": "SAN BERNABE (FOMERREY 112)"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA DOLORES ESPINOSA CARDONA",
  "NARVARTE": "SAN MARTIN"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA DOLORES PEREZ DE LARA SEPULVEDA",
  "NARVARTE": "JARDINES DEL CONTRY"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA EDNA PINALES CERVANTES",
  "NARVARTE": "GARZA NIETO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA ELENA GUZMAN CONTRERAS",
  "NARVARTE": "BALCONES DE ALTA VISTA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA ELENA HERNANDEZ MARTINEZ",
  "NARVARTE": "ARGENTINA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA ELENA PEREZ CHAVARRIA",
  "NARVARTE": "CERRO DE LA CAMPANA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA EMMA GARCIA RODARTE",
  "NARVARTE": "FRACCIONAMIENTO INDEPENDENCIA "
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA ESTHER ARRIAGA IBARRA",
  "NARVARTE": "NOGALES DE LA SIERRA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA ESTHER MARTINEZ PEÑA",
  "NARVARTE": "VALLE DEL MARQUEZ"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA FERNANDA PEREZ FALCON",
  "NARVARTE": "TERMINAL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA ISABEL MORALES LOZANO",
  "NARVARTE": "PROGRESO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA ISABEL VILLEGAS BLANCO",
  "NARVARTE": "FOMERREY 114"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA JOSEFINA GAMEZ RIOS",
  "NARVARTE": "REVOLUCION PROLETARIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA LETICIA RODRIGUEZ GARCIA",
  "NARVARTE": "CUMBRES LA JOYA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA LUISA ALONSO PALACIOS",
  "NARVARTE": "MODERNA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA LUISA HERNANDEZ DE HOYOS",
  "NARVARTE": "UNIDAD MODELO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA TERESA DELGADO CEJA",
  "NARVARTE": "SAN BERNABE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA TERESA GUERRA REYES",
  "NARVARTE": "CENTRAL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIA TERESA VILLARREAL ELIZONDO",
  "NARVARTE": "CENTRO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIO ALBERTO MARTINEZ MORIN",
  "NARVARTE": "BARRIO PUERTA DEL SOL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARIO HERNANDEZ MENDOZA",
  "NARVARTE": "MODERNA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARISOL HERNANDEZ ESPINO",
  "NARVARTE": "GENARO VAZQUEZ"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARTHA ALICIA PUENTE GONZALEZ",
  "NARVARTE": "FERROCARRILERA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARTHA ELVIA ZAVALA SANCHEZ",
  "NARVARTE": "PLUTARCO ELIAS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MARTHA LOPEZ ZARATE",
  "NARVARTE": "INDEPENDENCIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MAURILIO LOPEZ NUNCIO",
  "NARVARTE": "LA FLORIDA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MAYRA ALICIA PALOMO HERNANDEZ",
  "NARVARTE": "BENITO JUAREZ"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MELANIE PATRICIA MERAZ SIERRA",
  "NARVARTE": "SAN BERNABE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MINERVA RUGERIO GUTIERREZ",
  "NARVARTE": "VALLE VERDE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MIRIAM DOLORES DEGOLLADO GARCIA",
  "NARVARTE": "INDUSTRIAL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MIRTHALA MENDEZ DE LA ROSA",
  "NARVARTE": "FRANCISCO VILLA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "MONICA SALDAÑA HERNANDEZ",
  "NARVARTE": "FOMERREY 24"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "NANCY ANGELICA HERNANDEZ ESQUIVEL",
  "NARVARTE": "INDEPENDENCIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "NELIDA LEAL ROJAS",
  "NARVARTE": "BENITO JUAREZ"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "NOE JUAN CORONA SALDAÑA",
  "NARVARTE": "LA ALIANZA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "NOELIA SANCHEZ BUSTOS",
  "NARVARTE": "4 DE DICIEMBRE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "NOHEMI DEYANIRA PADILLA CANO",
  "NARVARTE": "VALLE DE SANTA LUCIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "NORA ANGELICA MENDOZA ESPINOSA",
  "NARVARTE": "HDA MITRAS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "NORMA ALVARADO PINALES",
  "NARVARTE": "PLUTARCO ELIAS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "OLGA NELLY RANGEL GONZALEZ",
  "NARVARTE": "LAS BRISAS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "PABLO ROBERTO CANTU GALVAN",
  "NARVARTE": "RESIDENCIAL LA ESPANOLA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "PATRICIA MIRELES BRICEÑO",
  "NARVARTE": "VALLE VERDE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "PATRICIA RAMIREZ CORONADO",
  "NARVARTE": "TALLERES"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "PRISCILA VANESSA CAMPOS LEAL",
  "NARVARTE": "PABLO A DE LA GARZA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "RAMON URBANO PIÑA LIZARRAGA",
  "NARVARTE": "VALLE DE LA PRIMAVERA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "RAMONA ALVAREZ GARCIA",
  "NARVARTE": "HOGARES FERROCARRILEROS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "RAQUEL CASTILLO ESCALONA",
  "NARVARTE": "TOPO CHICO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "RAYMUNDO LLANES RODRIGUEZ",
  "NARVARTE": "MIRASOL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "REBECA NIETO MARTINEZ",
  "NARVARTE": "CONQUISTADORES"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "REDUCINDO MENDOZA GONZALEZ",
  "NARVARTE": "LA PRIMAVERA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "RENE ESTALA CORONADO",
  "NARVARTE": "FOMERREY 1"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "REYNA ELIZABETH MARTINEZ DELGADO",
  "NARVARTE": "FRANCISCO I. MADERO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "REYNA IBARRA JASSO",
  "NARVARTE": "ALTAMIRA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "RICARDO MONCADA RODRIGUEZ",
  "NARVARTE": "LOS ROSALES"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ROBERTO ADRIAN ALEJO GARZA",
  "NARVARTE": "SAN JERONIMO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ROBERTO ALVISO MARQUES",
  "NARVARTE": "CENTRO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ROBERTO GALLARDO ARBALLO",
  "NARVARTE": "ESTADIO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ROBERTO SUAREZ ACOSTA",
  "NARVARTE": "REFORMA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ROCIO ANGELICA GONZALEZ CORTES",
  "NARVARTE": "LA FLORIDA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ROCIO ELIZABETH SALAZAR DELGADO",
  "NARVARTE": "10 DE MARZO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "RODOLFO MORENO AGUILAR",
  "NARVARTE": "INDEPENDENCIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ROSA ALEJANDRA RODRIGUEZ MENDEZ",
  "NARVARTE": "INDEPENDENCIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ROSA IMELDA VELAZQUEZ FRANCO",
  "NARVARTE": "MAS PALOMAS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ROSA MARIA HINOJOSA AGUIRRE",
  "NARVARTE": "VALLE DE LAS BRISAS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ROSENDO CARRASCO REYES",
  "NARVARTE": "SAN BERNABE"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "RUTH MARTINEZ XX",
  "NARVARTE": "FERROCARRILERA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "SALVADOR LEAL PAUL",
  "NARVARTE": "CUMBRES 2 SECTOR"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "SANDRA EDITH LOPEZ IRACHETA",
  "NARVARTE": "LOS ALTOS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "SANDRA NELLY ESQUIVEL FLORES",
  "NARVARTE": "VILLASOL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "SANDRA VERONICA DE LA CRUZ GAYTAN",
  "NARVARTE": "VALLE DE SANTA CECILIA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "SARA EUNICE LERMA SANCHEZ",
  "NARVARTE": "ARCOS DEL SOL"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "SARA MARGARITA TORRES SANTOS",
  "NARVARTE": "SAN JERONIMO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "SAUL IVAN CHIHUAHUA LUNA",
  "NARVARTE": "FOMERREY 106"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "SELENE YADIRA GARZA ESTRADA",
  "NARVARTE": "BARRIO ALAMEDA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "SILVANO SALAZAR NAVA",
  "NARVARTE": "LA FLORIDA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "SILVIA CORONA CASTILLON",
  "NARVARTE": "RESIDENCIAL LA LAGRIMA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "SILVIA NELLY HERNANDEZ HERNANDEZ",
  "NARVARTE": "CONTRY"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "SUSANA AIDE YATTES ALVARADO",
  "NARVARTE": "LOS CEDROS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "TERESA DE JESUS DIAZ OLVERA",
  "NARVARTE": "BUROCRATAS MUNICIPALES"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "TERESA DEL ROBLE ESTRADA CISNEROS",
  "NARVARTE": "MODERNA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "TERESA ESMERALDA SALAZAR ALVARADO",
  "NARVARTE": "EL PROVENIR"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "URBANO SALAZAR ORTIZ",
  "NARVARTE": "PROGRESO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "VERONICA LUNA LOPEZ",
  "NARVARTE": "VALPARAISO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "VICTOR ENRIQUE CEPEDA ALANIS",
  "NARVARTE": "ROMA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "VICTOR HUGO VELAZQUEZ HERNANDEZ",
  "NARVARTE": "FOMERREY 109"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "VICTOR MANUEL BAENA RODRIGUEZ",
  "NARVARTE": "VALLE DE LAS MITRAS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "VICTOR MANUEL GALLEGOS",
  "NARVARTE": "SAN BERNABE (FOMERREY 112)"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "VIRGINIA RAMOS PEREZ",
  "NARVARTE": "VALLE DEL MIRADOR"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "XIOMARA YAZMIN HERNANDEZ PINEDA",
  "NARVARTE": "BUENOS AIRES"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "YAHAIRA YESENIA JUAREZ ARANDA",
  "NARVARTE": "SIERRA VENTANA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "YESIKA GRACIELA LEAÑOS GARCIA",
  "NARVARTE": "BARRIO SAN CARLOS"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "YOKABETH GUEL ALONSO",
  "NARVARTE": "LA ALIANZA"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "YOLANDA MARICELA TAMAYO GARCIA",
  "NARVARTE": "FRANCISCO I. MADERO"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "YULIANA BERENICE ALEMAN SEGURA",
  "NARVARTE": "TIERRA Y LIBERTAD"
 },
 {
  "ADAN GERARDO GONZALEZ LEDEZMA": "ZAIRA YARELLY CALVILLO GONZALEZ",
  "NARVARTE": "LA ALIANZA"
 }
]
}
